### ISSUE TITLE
Behavior of checkpoint restore is confusing if used while the blockchain is running

### ISSUE THREAD

**Issue by djnicholson** [neo-project/neo-express#101]
If you restore a checkpoint while the blockchain is running, the command will be successful but new blocks will still be created based on the current chain.  When you stop and restart nxp3 you then see the restored state (and lose any blocks mined in the meantime).

I would expect that either checkpoint restoration be immediate, or that restores be blocked while the blockchain is running.

**Comment by devhawk** [comment]
checkpoint restoration is blocked while the node is running. Just verified this on Windows and WSL Ubuntu 20.04

**Comment by djnicholson** [comment]
Restore-while-running is not blocked on Mac as of 1.2.85-insiders

**Comment by devhawk** [comment]
> Restore-while-running is not blocked on Mac as of 1.2.85-insiders

Can you test a more recent build?

**Comment by djnicholson** [comment]
Will do...
