### ISSUE TITLE
MaxGasInvoke and MaxFee

### ISSUE THREAD

**Issue by gsmachado** [neo-project/neo-express#109]
Is there a way to set `MaxGasInvoke` and `MaxFee` in the [2.0.9-preview](https://github.com/neo-project/neo-express/releases/tag/2.0.9-preview) release (I mean, directly in `default.neo-express` file)? Check [this](https://github.com/neo-project/neo-modules/blob/master/src/RpcServer/RpcServer/config.json#L13-L14).

This is important for integration tests, depending on the smart contract and use case the developer is trying to achieve.

**Comment by gsmachado** [comment]
The `invoke` JSON-RPC call is **very** useful for SDKs where estimates fees, for example. However, the default `MaxGasInvoke` is sometimes a bit low, depending on the smart contract that is being developed.

That's why we increased the `MaxGasInvoke` option in our [neo3-privatenet-docker](https://github.com/AxLabs/neo3-privatenet-docker) -- more specifically [in this file](https://github.com/AxLabs/neo3-privatenet-docker/blob/master/config/rpcserver.config-consensus.json).

Naturally, setting a custom `MaxGasInvoke` should only be used in a test environment -- which `neoxp` is all about. 😄

**Comment by devhawk** [comment]
No, there is no way to do this in neo express currently. But it certainly is a good suggestion.

**Comment by gsmachado** [comment]
Great to hear!

I would say that this becomes a fundamental feature for SDKs like neon-js, neow3j, etc., otherwise it becomes impractical to use and integrate with `neoxp`. The decrease of `MaxGasInvoke` and `MaxFee` became effective only in neo3-preview5.

**Comment by csmuller** [comment]
This would be very useful for tests, e.g., where we need calls to `NeoToken.registerCandidate(...)`. That example overflows the default `MaxGasInvoke` by far.

**Comment by gsmachado** [comment]
Yeah, that's a good use case, @csmuller.

I think that `MaxGasInvoke` was set to a lower default amount due to safety reasons (maybe prevent stability/load issues on nodes?), which makes sense.... but then, it makes people adjust it depending on the use case.
