### ISSUE TITLE
Setting signer scopes

### ISSUE THREAD

**Issue by csmuller** [neo-project/neo-express#115]
I tried to deploy a contract with `neoxp contract deploy /path/to/contract.nef SigningAccount`. The contract defines an owner address and in its `_deploy` method it calls `CheckWitness` to check if the singer of the deploy transaction is the owner. 
With the above command the `CheckWitness` call fails. The deployment transaction has a signer with witness scope `CalledByEntry`. When I do the deployment with other means and use the `Global` signer scope, the deployment transaction is successful. 

Is there a way to set the signer scope on neo-express commands like `contract deploy` or `contract invoke`?

**Comment by devhawk** [comment]
There is not, but I agree there should be. `contract deploy` and `contract invoke` commands should allow developers to specify witness scope. 

I don't think we want to get into specifying custom contracts/groups on the command line. For those scenarios, developers can construct their transactions as they see fit and submit via SendRawTx RPC endpoint.

I propose adding a --witness-scope (short form -w) option to those commands. The option would support three values: None, Global and CalledByEntry. CalledByEntry would be the default if unspecified.

Question: do we need to enable --witness-scope option for any other commands besides `contract deploy` and `contract invoke`?

**Comment by csmuller** [comment]
> I don't think we want to get into specifying custom contracts/groups on the command line. For those scenarios, developers can construct their transactions as they see fit and submit via SendRawTx RPC endpoint.

Agreed!

> I propose adding a --witness-scope (short form -w) option to those commands. The option would support three values: None, Global and CalledByEntry. CalledByEntry would be the default if unspecified.

I also agree on this. It makes sense to have it as an option and not as a mandatory argument. And CalledByEntry as the default value is fine.

> Question: do we need to enable --witness-scope option for any other commands besides contract deploy and contract invoke?

No, it seems only reasonable for the `deploy` and `invoke` commands. More complex transfers, e.g. withdrawing tokens from a smart contract, are not possible anyway with the `neoxp transfer` command, thus I don't think the `transfer` command needs the witness scope option.
