### ISSUE TITLE
Offline SendRawTx equivalent

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-express#117]
One of the main value props of Neo Express is that it runs the same code as the neo mainnet nodes (i.e. neo.dll + relevant official modules like RpcServer). So if the command line doesn't support a given scenario, you can always create a transaction yourself and submit via RPC `SendRawTransaction`.

However, `SendRawTransaction` is only available when the node is running. Should their be an offline equivalent to RPC `SendRawTransaction`? If so, how should it work?

**Comment by gsmachado** [comment]
@devhawk you mean, a way to send a raw transaction that is persisted directly on-chain (disk)?

**Comment by devhawk** [comment]
I don't know if i want to persist it on disk - id rather pass it over stdin. But basically, yes. Today, you can construct an arbitrary transaction and submit to a running neoxp instance via the SendRawTX rpc method. I'm thinking offline mode needs a similar mechanism

**Comment by gsmachado** [comment]
Well, in this case, if the node is not running at all and a tx should be sent to the chain, I think that using stdin is the way. I would also add an option to specify a file input or something to specify the raw transaction.

Another possibility -- which I don't know if it's feasible tbh -- is to allow users to specify JSON-RPC request files. Then, all functions provided by the RpcServer would be available in the offline mode. This would be the most generic solution.

Example:

```
{
  "jsonrpc": "2.0",
  "method": "sendrawtransaction",
  "params":["80000000019b7cffdaa674beae0f930ebe6085af9093e5fe56b34a5c220ccdcf6efc336fc500ca9a3b00000000295f83f83fc439f56e6e1fb062d89c6f538263d70141407f2dc9470e0b9ce969298d6c03f2141b3165ce43983dc210dbedee7b3aa080d7f4c1e454c0deb2865eac67c0ee9d8b5b77351c99ad090e825a839988934eab9f23210265bf906bf385fbf3f777832e55a87991bcfbe19b097fb7c5ca2e4025a4d5e5d6ac"],
  "id": 1
}
```

What do you think?

**Comment by devhawk** [comment]
> Another possibility -- which I don't know if it's feasible tbh -- is to allow users to specify JSON-RPC request files. 

neo-express already supports [contract invocation JSON files](https://github.com/ngdenterprise/design-notes/blob/master/NDX-DN12%20-%20Neo%20Express%20Invoke%20Files.md) so I don't think the JSON-RPC wrapper adds much. And frankly, I'm not even sure if we need an offline sendRawTx equivalent. But I thought of it at one point and made the issue so I wouldn't forget.
