### ISSUE TITLE
Write a known message to the console once the DB lock has been acquired

### ISSUE THREAD

**Issue by djnicholson** [neo-project/neo-express#123]
The DevTracker needs to start neo-express then immediately run some other `neoxp` commands.  It is important that the subsequent commands are not run until the `neoxp run` command has acquired the database lock (or the process will fail and exit).

It would be good if a specific message was printed to the console to acknowledge this state, and have the contents of the message be guaranteed to be fixed.

See: https://github.com/ngdenterprise/neo3-visual-tracker/pull/58

**Comment by devhawk** [comment]
neoxp already writes out the storage provider type (RocksDbStorageProvider or CheckpointStorageProvider) on run. The core neo consensus node log starts with `<timestamp> ConsensusService Info OnStart`. Do either of those work?

```
$ dotnet neoxp run
RocksDbStorageProvider
15:50:27.23 ConsensusService Info OnStart
15:50:27.25 ConsensusService Info Initialize: height=1 view=0 index=0 role=Primary  
15:50:27.25 ConsensusService Info Sending RecoveryRequest: height=1 view=0 nc=0 nf=0
15:50:27.26 ConsensusService Info Sending PrepareRequest: height=1 view=0
15:50:27.27 ConsensusService Info Sending Commit
15:50:27.27 ConsensusService Info Sending Block: height=1 hash=0x2121cbac97e74c469da0066cdd631d421899ad4f77e5075d29a9db97f7f59d14 tx=0
15:50:27.28 ConsensusService Info Persisted Block: height=1 hash=0x2121cbac97e74c469da0066cdd631d421899ad4f77e5075d29a9db97f7f59d14 tx=0
15:50:27.28 ConsensusService Info Initialize: height=2 view=0 index=0 role=Primary
... remaining log omitted ...
```

**Comment by djnicholson** [comment]
I was hoping to have something more explicit, e.g.:

```
// DevTracker looks for this exact string to confirm that the instance has started, do
// not remove or re-word this console output:
Console.WriteLine("Neo express is running"); 
```

Just trying to maintain a contract between the DevTracker and neo-express, and prevent a hard-to-debug DevTracker issue if one of the underlying libraries used by neo-express changes some aspect of its logging in the future.
