### ISSUE TITLE
I can't start Neo Express.

### ISSUE THREAD

**Issue by picarodias** [neo-project/neo-express#124]
I followed this tutorial: https://ngdenterprise.com/neo-tutorials/tutorial1-ui.html

Installed everything, but can't run the private blockchain using Neo Express. When I click Start Neo Express I get the following error:

![image](https://user-images.githubusercontent.com/68299002/113646495-4e05e200-965f-11eb-9575-26601a98a8e1.png)

And the Visual Dev Tracker never finishes loading:

![image](https://user-images.githubusercontent.com/68299002/113646628-8f968d00-965f-11eb-978a-ed68280861ca.png)

Can someone help me?

Edit: I'm using MacOS High Sierra

**Comment by devhawk** [comment]
@picarodias is this an M1 or intel based Mac?

**Comment by devhawk** [comment]
Also, @picarodias can you try working thru this command line tutorial so I can get more info on why neo express is failing? https://ngdenterprise.com/neo-tutorials/tutorial1-cmd.html

**Comment by EdgeDLT** [comment]
@devhawk I was also struggling to get the latest version of Express to run on Ubuntu 18 (both from command line and in DevTracker).

Error was:

 `The type initializer for 'RocksDbSharp.Native' threw an exception`

Fixed using:

`sudo apt-get install librocksdb-dev`

**Comment by devhawk** [comment]
Yes, we recently added that to our [ubuntu specific install instructions](https://github.com/neo-project/neo-express#ubuntu-installation) (thanks @metachris!)
