### ISSUE TITLE
Unable to use `neoxp run` because there is no Neo-Express folder on AppData/Local

### ISSUE THREAD

**Issue by melanke** [neo-project/neo-express#128]
I am installig the tools on a new computer and had this problem.

How to reproduce:
```
$ dotnet tool install Neo.Express -g --add-source https://pkgs.dev.azure.com/NGDSeattle/Public/_packaging/NeoPublicPackages/nuget/v3/index.json --version 2.0.21-preview
$ mkdir hello_world
$ cd hello_world
$ neoxp create
$ neoxp run
```
The error output is:
```
IO error: No such file or directoryFailed to create a directory: 
C:\Users\Avell\AppData\Local\Neo-Express\blockchain-nodes\NWRm6aV7EMieGodmR6P93Beto5FMSgoLQB:
The system could not find the specified path.
```
---
I am not sure when this folder is created, I have a friend that runs Neo-Express without it, and another friend that could zip his folder and send to me, and after creating it on my computer the command works fine.

**Comment by devhawk** [comment]
This was fixed by #126. Install version ` 2.0.23-preview` or later to get the fix
