### ISSUE TITLE
Feature request: Allow filenames to be supplied for arguments in invoke files

### ISSUE THREAD

**Issue by djnicholson** [neo-project/neo-express#130]
It would be very convenient if a user could specify a path to a file as an argument and then have Neo Express read the raw bytes of that file and use this data when constructing the invocation transaction.

This would be useful when updating a contract (you can have a static invoke file that references the .nef and .json manifest within your build output directory and invoke it after a build)

**Comment by devhawk** [comment]
FYI, this is a https://github.com/ngdenterprise/neo-blockchaintoolkit-library feature
