### ISSUE TITLE
The type initializer for 'RocksDbSharp.Native'

### ISSUE THREAD

**Issue by vpereira** [neo-project/neo-express#134]
```
$ neoxp run
The type initializer for 'RocksDbSharp.Native' threw an exception.
$ neoxp --version
2.0.23-preview+44a83bc8bf
```

**Comment by devhawk** [comment]
@vpereira what platform are you running?

**Comment by vpereira** [comment]
Hi @devhawk, I'm using in the end openSUSE Linux, running on windows, via subsystem. Installing the `rocksdb` package offered by SUSE, was enough to make it work.
