### ISSUE TITLE
Support additional commands within `neoxp batch`

### ISSUE THREAD

**Issue by djnicholson** [neo-project/neo-express#143]
I think it would be useful if batch supported any command other than `create`/`run`.

I was trying to arrange for the msbuild for my test project to create a new blockchain in a known state ready for the tests to run on but could not use `wallet create` within a batch file.

**Comment by devhawk** [comment]
I don't follow why you would create a wallet in batch run. I typically create wallets interactively, then commit the .neo-express file to source control. Wallet *contents* are reset when the blockchain is reset, but the actual wallet itself still exists

**Comment by djnicholson** [comment]
This is for unit testing.  I have the MSBuild project for the test DLL create an entirely new .neo-express config (to ensure the tests always run with a consistent config).  To see an example of what I am describing, create a new C# contract using the DevTracker and take a look at the skeleton unit test project that gets created.
