### ISSUE TITLE
Add STOP command?

### ISSUE THREAD

**Issue by roschler** [neo-project/neo-express#153]
I'd like to see `neoxp` have a STOP command that stops the currently active NEO Express instance.  That way we could use it as a ".csproj" _Exec_ Exec command before running other commands against the Express instance.  In other words, the equivalent of the "Stop Blockchain" option available from the NEO Express instance right-click menu in the N3 Visual Studio Code UX.

**Comment by devhawk** [comment]
Adding a stop command would enable node shutdown integration w/ the build system
