### ISSUE TITLE
Add a command line option to `neoxp run` that causes console logging when a transaction causes a VM `FAULT`

### ISSUE THREAD

**Issue by djnicholson** [neo-project/neo-express#155]
The DevTracker could parse this extra output and show warn the user through the VS Code UI, see: https://github.com/ngdenterprise/neo3-visual-tracker/issues/108

**Comment by devhawk** [comment]
The Blockchain actor publishes ApplicationExecuted messages to the Akka EventStream. It would be straightfoward to listed for said messages and write a message to the log if the transaction faulted. 

However, I'd rather not add a new command line option for this. I assume we're OK with just *always* logging faults to the console?

**Comment by djnicholson** [comment]
> However, I'd rather not add a new command line option for this. I assume we're OK with just always logging faults to the console?

That seems reasonable as the log is already reasonably noisy.

We probably don't need to be that strict about the format of the message either:  Neo Express could write to stderr instead of stdout and the devtracker could assume each line of output on stderr is an error to show to the user.

**Comment by devhawk** [comment]
@djnicholson here's an example output from #159. Does this look OK?

```
12:07:35.79 ExpressChainManager Error Tx FAULT: hash=0x3773325b5006c012b553b7e26fc6a091d3c41c5f47c8e43f98795e3847b99cef exception="An unhandled exception was thrown. Specified token already owned"
```

**Comment by devhawk** [comment]
No, it's using the existing neo logging infrastructure, so it goes to stdout. does that still work?

**Comment by djnicholson** [comment]
stderr would be better (then every line to stderr could be treated as an error with no parsing required).

If it has to be stdout then we should have some agreement on the format (and a comment in the code on the Neo Express side so that the DevTracker isn't inadvertently broken in the future).  Maybe just presence of "Error" anywhere in the line? (Or could that happen in non-error cases?)
