### ISSUE TITLE
Add an RPC endpoint to return a bitmap of known empty blocks

### ISSUE THREAD

**Issue by djnicholson** [neo-project/neo-express#16]
This will make it more efficient for the vscode devtracker to hide empty blocks.

**Comment by devhawk** [comment]
probably makes more sense to return a list of non-empty blocks doesn't it?

**Comment by djnicholson** [comment]
> probably makes more sense to return a list of non-empty blocks doesn't it?

Yes!

**Comment by devhawk** [comment]
preliminary implementation in devhawk/populatedblocks branch adds a new `express-get-populated-blocks` RPC endpoint that returns an unordered array of block indexes that contain more than one transaction. 

example request:
``` json
{
  "jsonrpc": "2.0",
  "method": "express-get-populated-blocks",
  "params": [],
  "id": 1
}
```

example response:
``` json
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": [
    282, 341, 140, 327, 239, 262, 278, 309, 295, 223, 
    311, 298, 280, 132, 218, 7, 275, 323, 312, 314,
    297, 0, 246, 325, 277, 267
  ]
}
```
