### ISSUE TITLE
--trace support for oracle response command

### ISSUE THREAD

**Issue by kokahunter** [neo-project/neo-express#183]
Would be nice to be able to `neotrace tx 0x..f --rpc-uri http://localhost:50012`. 

I want to debug an oracle response transaction on neo express private net. Command responding with `Method not found`.

**Comment by devhawk** [comment]
Thanks for the suggestion @kokahunter! 

Neo-express doesn't implement the state service code needed for `neotrace`. However, it does have the infrastructure for generating trace files when contracts are executed. *Most* of the contract execution operations support a --trace argument. However, `oracle response` does not. Oversight on our part. WIll fix.
