### ISSUE TITLE
NEP11/17 contract validator

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-express#194]
We could validate that a contract that declares that it implements NEP11 or NEP17 has an interface that conforms to the relevant standard

**Comment by chenzhitong** [comment]
I guess this should only be verified by source code, otherwise how can you verify that the contract is correctly implementing some NEP11/17 method, such as transfer method, even though he implements the interface but uses the wrong logic, so that there's no way for the program to detect it.

**Comment by cschuchardt88** [comment]
https://github.com/neo-project/proposals/blob/master/nep-11.mediawiki

Validate against the spec.
