### ISSUE TITLE
Can not transfer to a contract

### ISSUE THREAD

**Issue by luc10921** [neo-project/neo-express#197]
Trying to use `neoxp transfer 1 gas alice #smartcontract` will not work and sends the following error message: `System.Exception: #smartcontract account not found.`
Trying to do the opposite `neoxp transfer 1 gas #smartcontract alice`, will also not work, and it asks: `enter password for #smartcontact` and then it send the following error: `System.Exception: #smartcontract sender not found.`

**Comment by devhawk** [comment]
I don't think we can support using a contract as a Sender, but we should be able to support it as a receiver.
