### ISSUE TITLE
Neoxp can't export genesis wallet

### ISSUE THREAD

**Issue by lock9** [neo-project/neo-express#200]
Hi,

I can view my 'node1' wallet when I use `neoxp wallet list`, but I can't export it. 
Error: `node1 express wallet not found.`

Thanks

**Comment by devhawk** [comment]
There isn't a "genesis" wallet. genesis is a special designation for the multi-sig account shared by the consensus nodes (even where there is only a single consensus node).

The consensus node wallets can't be exported with `wallet export` but all the consensus node wallets can be exported by the `export` command
