### ISSUE TITLE
Can I access Neo express via LAN？

### ISSUE THREAD

**Issue by jack9684** [neo-project/neo-express#229]
Can I access Neo express via LAN? 127.0.0.1:50012 is not used. Use 192.168 X.X:50012. I use telnet. This port doesn't work

**Comment by ixje** [comment]
Access with what? Assuming a default `default.neo-express` configuration then `50012` is the RPC port. Works fine here
```
telnet 127.0.0.1 50012
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
```
You must supply valid json-rpc input to get a response, see https://docs.neo.org/docs/en-us/reference/rpc/latest-version/api.html

If you want to connect with another neo-cli instance then then the tpc port is `50013`
```
telnet 127.0.0.1 50013
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
(?r��9ab+
         3E
           /Neo:3.1.0/U]�^
```

Are you sure the neo-express instance is actually started (`./neoxp run -i default.neo-express`)?

**Comment by devhawk** [comment]
Yes. 

From https://github.com/neo-project/neo-express/blob/master/docs/settings.md#rpcbindaddress

> By default, Neo-Express only listens for JSON-RPC requests on the loopback address. This means that JSON-RPC requests must originate on the same machine as Neo-Express is running in order to be serviced. While this is the most secure approach, it limits the ability of the developer to test cross machine scenarios, especially ones that involve mobile devices. The rpc.BindAddress setting can be used to override the default behavior.
