### ISSUE TITLE
List the available operations and arg types in the interactive invoke menu when using contract download

### ISSUE THREAD

**Issue by EdgeDLT** [neo-project/neo-express#240]
I really like having the available functions and parameter types for deployed contracts that I've compiled locally. Though my main use for `contract download` will be for testing contracts that call the downloaded contracts, being able to quickly invoke them with the GUI is useful at times too.

I assume this data is populated using the manifest, one extra call to `getcontractstate` during `contract download` should be enough to fetch the ABI.

Actually I noticed that I don't have this info for native contracts either, though I'm fairly certain they used to be there. Maybe a bug?

**Comment by devhawk** [comment]
THis appears to be a devtracker issue
