### ISSUE TITLE
wallet create with deterministic private key

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-express#248]
`wallet create` command calls `Wallet.CreateAccount` which generates a private key using `RandomNumberGenerator`. for some dev scenarios, it would be useful to support a deterministic private key - either provided by the user or generated by hashing the account name

**Comment by lock9** [comment]
I think this was implemented without proper discussion. The PR also lacks documentation, UTs and others. I know that the guidelines were not approved yet, but let's avoid doing this. Are we creating deterministic accounts? Are the accounts on Neo express today deterministic?

**Comment by cschuchardt88** [comment]
Only if you create them. 😃 

>either provided by the user or generated by hashing the account name

What was implemented? `By the user`
