### ISSUE TITLE
contract download --height help text

### ISSUE THREAD

**Issue by ixje** [neo-project/neo-express#249]
```
  -h|--height <HEIGHT>  Block height to get contract state for
                        Default value is: 0.
```
The "default value" part of the help text is a bit confusing in the sense that it does not inform the user that "0" means, get latest.

**Comment by chenzhitong** [comment]
There seems to be no `contract download` in the command reference. Need to add

**Comment by cschuchardt88** [comment]
@chenzhitong 

https://github.com/neo-project/neo-express/blob/a07ab649ac86cbb313485632790468075e1a9805/src/neoxp/Commands/ContractCommand.Download.cs#L37-L38
