### ISSUE TITLE
contract download - remove exception on empty validatedrootindex 

### ISSUE THREAD

**Issue by ixje** [neo-project/neo-express#251]
The `contract download`  feature is intended to support local development. There is a security check that seems unnecessary when used for this purpose, specifically here

https://github.com/neo-project/neo-express/blob/c6424c0441c871dd2e5d4aaf132c3abde3b7abb7/src/neoxp/Node/NodeUtility.cs#L244-L245

this basically forbids using any node that is not voted into the list of state validators by the consensus committee. It should be possible to use nodes that you trust e.g. I want to use our COZ nodes because the NEO nodes are very slow. This could be done by using `localrootindex` instead of `validatedrootindex`.

I see 3 ways of solving this
1. always use `localrootindex` instead of `validatedrootindex`
2. have a flag like `--allow-localroot` to use `localrootindex` if `validatedrootindex` is `null`
3. the inverse of 2. where we allow `localrootindex` by default unless passing some flag like `--require-rootvalidated-state`

**Comment by devhawk** [comment]
I wouldn't characterize this as a security check. If the user doesn't explicitly specify a block height to download, the command gets "most recent available". *How* the command chooses "most recent available" doesn't seem that critical.

How about a slight variation on option 1: Use `localrootindex` if `validatedrootindex` is not available. Something like this maybe?

``` cs
if (stateHeight == 0)
{
    uint? localRootIndex, validatedRootIndex;
    try
    {
        (localRootIndex, validatedRootIndex) = await stateAPI.GetStateHeightAsync().ConfigureAwait(false);
    }
    catch (RpcException e) when (e.Message.Contains("Method not found"))
    {
        throw new Exception(
            "Could not get state information. Make sure the remote RPC server has state service support");
    }

    stateHeight = validatedRootIndex.HasValue 
        ? validatedRootIndex.Value
        : localRootIndex.HasValue
            ? localRootIndex.Value
            : throw new Exception($"GetStateHeight did not return local or validated root index");
}
```

**Comment by devhawk** [comment]
FYI, can use null coalesce operator instead:

```cs
stateHeight = validatedRootIndex ?? localRootIndex 
    ?? throw new Exception($"GetStateHeight did not return local or validated root index");
```
