### ISSUE TITLE
getapplicationlog response differs from neo-cli

### ISSUE THREAD

**Issue by ixje** [neo-project/neo-express#255]
When a transaction or block cannot be found neoxpress gives the following error message (rpc exception)
> Unknown transaction

whereas neo-cli/neo-go return 
> Unknown transaction/blockhash

I ran into it because my code was testing against the full exception message

**Comment by cschuchardt88** [comment]
Can you provide the commands you running?

**Comment by ixje** [comment]
use the `getapplicationlog` RPC method to try and get a transaction that you know doesn't exist on that network (e.g. `0xdf349e0de5f4fa30f05e3edd40095aab44566a4d37cd1b636d54cc375004875a`)

**Comment by cschuchardt88** [comment]
If you are referring to `neoxp.exe show transaction 0xdf349e0de5f4fa30f05e3edd40095aab44566a4d37cd1b636d54cc375004875a` then yes that can be changed.

**Comment by ixje** [comment]
i'm referring to the RPC method returning a different response to the C# implementation
specifically here
https://github.com/neo-project/neo-express/blob/de55d4f17fa7c17b13014f4652a8d447dd3005ef/src/neoxp/Node/Modules/ExpressRpcServerPlugin.cs#L350

vs the reference
https://github.com/neo-project/neo-modules/blob/4f55458bda29a0e80258add2a3768dcc014ab24d/src/ApplicationLogs/LogReader.cs#L64

**Comment by cschuchardt88** [comment]
Well how are you running the `neo-express` node? Cause above i added the `GetApplicationLog` plugin to the `Plugins` directory to get RPC method to work. And i do get the error you are talking about.

**Comment by ixje** [comment]
`getapplicationlog` is a build in method, see the source linked. I just run neoxp and call the RPC method e.g.
<img width="683" alt="image" src="https://github.com/neo-project/neo-express/assets/6625537/a3606376-9d48-4290-bc25-884796cedda3">
