### ISSUE TITLE
support contract name as source/destination in batch transfer

### ISSUE THREAD

**Issue by ixje** [neo-project/neo-express#256]
NEP17/11 tokens often accept tokens (e.g. NEO) in return for their token or NFT. Say we deploy a contract
```
contract deploy ./token-contract/bin/sc/NeoContributorToken.nef owen
```

and now want to `transfer` NEO to the just deployed contract (as a means of minting). You currently can't do that conveniently from the batch file. Ideally you'd be able to do
```
transfer 100 neo owen NeoContributorToken
```

**Comment by Ashuaidehao** [comment]
You can try to add a '@' prefix to search by contract name(not file name), and make sure there's no duplicated name contract onchain.

```
transfer 100 neo owen @NeoContributorToken
```

**Comment by cschuchardt88** [comment]
Just use the hash? or you want name?

https://github.com/neo-project/neo-express/blob/3e6fd5851a32514c3d303e26c095c4a6146bb27e/src/neoxp/Extensions/ExpressNodeExtensions.cs#L195-L220
