### ISSUE TITLE
Better output for RocksDbSharp.Native TypeInitializationException 

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-express#259]
Using Express on Mac or Linux carries [additional installation requirements](https://github.com/neo-project/neo-express#additional-neo-express-requirements). We should provide additional information - and perhaps a trouble shooter - when express can't locate the native rocksdb library

**Comment by chenzhitong** [comment]
Maybe it can be fixed with this issue https://github.com/neo-project/neo-express/issues/268 This way we no longer need to install dependencies

**Comment by cschuchardt88** [comment]
If you are talking about error `System.TypeInitializationException: The type initializer for 'RocksDbSharp.Native' threw an exception.` Its only for `x86 32-bit` which makes me believe that `RocksDbSharp.dll` doesn't support `x86 32-bit` CPUs.

**Comment by cschuchardt88** [comment]
I'll be working on this soon please add `enhancement` label
