### ISSUE TITLE
neo-express as a standalone native binary executable

### ISSUE THREAD

**Issue by gsmachado** [neo-project/neo-express#268]
As a user, I would like to:

1. Download `neo-express` binary for my arch (i.e., `darwin/amd64`, `darwin/arm64`, `linux/amd64`, or `window/amd64`).
2. Use `neo-express` command line straight away.

That's it.

If this is not possible, introducing the additional step of:
* Download minimum dependencies (like shared libs) using `brew` or `apt-get` (except `dotnet` or `java` or any other runtime).

would also be a great benefit compared to what we have nowadays.

**Comment by chenzhitong** [comment]
Support. This allows me to specify the directory where the program is installed instead of the default installation location of the dotnet tool. This also makes it easier to remove it.

**Comment by lock9** [comment]
Hi @chenzhitong , I think this should be a top priority. Neo-express can be compiled into a standalone application using the following command: `dotnet publish -c Release -r win-x64 --self-contained true`. This will generate a folder with neo-express and all its dependencies, including the .NET runtime.
It could be transformed into one or two files instead of a folder full of files. However, this is not currently supported. Something related to plugins, I'm not sure what, but I suspect it's related to the dynamic library loading. Not relevant for now.

The publishing workflow must be updated to use these commands and make the binaries available here.

**Comment by chenzhitong** [comment]
OK, I'll try it

**Comment by chenzhitong** [comment]
<img width="1280" alt="image" src="https://github.com/neo-project/neo-express/assets/6295602/1ca7b4ed-0585-40e1-a26b-997c25563c1f">
 @lock9 Do you know what this error is about?

**Comment by lock9** [comment]
@chenzhitong I think these URLs changed. 
Check the changes in this PR to see if it can help you:
https://github.com/neo-project/neo-express/pull/286/files

**Comment by lock9** [comment]
![image](https://github.com/neo-project/neo-express/assets/38396062/2fbafbad-21ee-4002-a895-de0775340f8d)

You can also try to set the target framework to use .NET 7.0, but I don't know how much this will help.

**Comment by chenzhitong** [comment]
It seems to be successful
This is packaged into a file, but requires .net framework dependencies: 
<img width="735" alt="image" src="https://github.com/neo-project/neo-express/assets/6295602/5a825e02-943f-4d0e-9fda-76b17cb2b9f6">
This is packaged into a file, but does not require .net framework dependencies:
<img width="692" alt="image" src="https://github.com/neo-project/neo-express/assets/6295602/3ac43a50-8ddb-45b8-9eb3-66279bb23c63">

**Comment by lock9** [comment]
If you are using Visual Studio, you need to set this option here. Select Self Contained instead of Framework Dependent
![image](https://github.com/neo-project/neo-express/assets/38396062/09fa335f-e4c2-4b6e-b4c1-8724a50b37a2)

**Comment by lock9** [comment]
If you are talking about the 'single file mode', this won't work if you try to run. You can test it by creating and starting a network. It will fail with a plugin error message (it would be great if you could get that error message)

**Comment by chenzhitong** [comment]
you are right
<img width="725" alt="image" src="https://github.com/neo-project/neo-express/assets/6295602/7075a70f-0574-414c-98d0-c6f9dd7dc322">

**Comment by lock9** [comment]
We can still ship it without the single file mode. It's ok if it's a zipped folder as long as it works.

**Comment by chenzhitong** [comment]
Target Framework | Deployment mode | Target runtime |   | Remark
-- | -- | -- | -- | --
net 7.0 | Self-contained | win-x64 | Single file mode | System.TypeInitializationException: The type initializer for   'Neo.Plugins.Plugin' threw an exception.
net 7.0 | Self-contained | win-x64 |   | Success
net 7.0 | Self-contained | win-x86 | Single file mode | System.TypeInitializationException: The type initializer for   'RocksDbSharp.Native' threw an exception.
net 7.0 | Self-contained | win-x86 |   | System.TypeInitializationException: The type initializer for   'RocksDbSharp.Native' threw an exception.
net 7.0 | Framework-dependent | portable |   | Success
net 7.0 | Framework-dependent | win-x64 | Single file mode | System.TypeInitializationException: The type initializer for   'Neo.Plugins.Plugin' threw an exception.
net 7.0 | Framework-dependent | win-x64 |   | Success
net 7.0 | Framework-dependent | win-x86 | Single file mode | System.TypeInitializationException: The type initializer for   'RocksDbSharp.Native' threw an exception.
net 7.0 | Framework-dependent | win-x86 |   | System.TypeInitializationException: The type initializer for   'RocksDbSharp.Native' threw an exception.

**Comment by lock9** [comment]
Hi @chenzhitong,

Now that you built it, we need to discuss how to distribute it. We also have to build it for macOS and Linux.

Regarding distribution: The simplest option is to distribute it here on GitHub. I think we will need other issues to talk about it, like:

- Distribute Neo Express on Brew
- Distribute Neo Express on Chocolatey
- Distribute Neo Express on Aptitude
- Distribute Neo Express on NeoFS
- Distribute Neo Express on Neo's Website
...

Let's try to consider this issue as the GitHub distribution.
Can you update the release workflow to build it using the new method and upload the artifacts here on GitHub? 
You will likely have to update this file here: https://github.com/neo-project/neo-express/blob/master/.github/workflows/release.yml

**Comment by cschuchardt88** [comment]
Is this repo not building right? I thought i had all that fixed. I said many times the [neo-blockchaintoolkit-library](https://github.com/N3developertoolkit/neo-blockchaintoolkit-library) is the one that needs to move to this repo. That is really neo-express. neo-express just a manager and maintains/manages the configuration files and console tooling.

**Comment by steven1227** [comment]
> Is this repo not building right? I thought i had all that fixed. I said many times the [neo-blockchaintoolkit-library](https://github.com/N3developertoolkit/neo-blockchaintoolkit-library) is the one that needs to move to this repo. That is really neo-express. neo-express just a manager and maintains/manages the configuration files and console tooling.

Is this necessary? We can move but it makes this repo much redundant which contains several small subprojects

**Comment by lock9** [comment]
It is building, but we are making it 'framework dependent'. We wish to move to a standalone build so users can run it without having to install the .NET SDK

**Comment by Liaojinghui** [comment]
I agree with @cschuchardt88, similar issue exists in the neo core, dependencies here and there, better to put everything togther.

**Comment by cschuchardt88** [comment]
Works fine for me 
![image](https://github.com/neo-project/neo-express/assets/8141309/ab9a947f-040c-4af5-b6d9-650f5162b231)

**Comment by chenzhitong** [comment]
> Works fine for me ![image](https://user-images.githubusercontent.com/8141309/280582529-ab9a947f-040c-4af5-b6d9-650f5162b231.png)

It can starts, but gives errors when running, you can try `neoex run`

**Comment by cschuchardt88** [comment]
Ok thats because `TypeInitializationException is usually caused by an error in static field initialization or static constructor execution.`

**Comment by cschuchardt88** [comment]
```
PS C:\Users\Chris\Projects\cschuchardt88\neo-express\src\neoxp\bin\Debug\net7.0\win-x64\publish> .\neoxp.exe run
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2)
   at Neo.Plugins.Plugin..cctor()
```

Need to put issue in for neo core to fix

**Comment by cschuchardt88** [comment]
Problem fixed `System.TypeInitializationException: The type initializer for 'Neo.Plugins.Plugin' threw an exception.`
![image](https://github.com/neo-project/neo-express/assets/8141309/5f00ce4a-4d97-4030-92f8-d01d36ec8204)

just need to get `neo` core to do my fix or i guess I'll do it.

**Comment by lock9** [comment]
Thank you @cschuchardt88 ! Can you check if the RPC server is also working? It depends on the plugins. Thank you!

**Comment by cschuchardt88** [comment]
I believe this for all plugins seeing how the error is for the static portion of the class.

**Comment by lock9** [comment]
Cool. Could you update the existing workflow to generate these binaries as part of the publish process? So we can download it from the releases page

**Comment by cschuchardt88** [comment]
The problem is in the `neo` core dll. need to wait for that merge to happen.

**Comment by cschuchardt88** [comment]
Also as for `System.TypeInitializationException: The type initializer for 'RocksDbSharp.Native' threw an exception.` I believe RocksDb is written for `x64` that's the reason why we get the error. Plus you may want to consider not doing `x86` because `x86` isn't supported nor is CPUs made for `x86` anymore. Also we don't own that repo.

**Comment by lock9** [comment]
I can confirm that the binaries are working for Windows and OSX. I didn't test the Linux version.

**Comment by cschuchardt88** [comment]
`RocksDbSharp.dll` current version is `6.2.2`

But the one that is included in the `blockchain-toolkit-library` is version `7.7.3.33461`. This could be a custom or updated one that @devhawk added. This could be the problem why its not working for `x86` `32-bit`.

**Comment by cschuchardt88** [comment]
@gsmachado In testing stage #357 But seems to be working ok now with new release of `neo` 3.6.2

**Comment by gsmachado** [comment]
> @gsmachado In testing stage #357 But seems to be working ok now with new release of `neo` 3.6.2

awesome! 
team work makes "dream work". 😃

**Comment by cschuchardt88** [comment]
@Liaojinghui @lock9 @gsmachado 
I don't know how to make `brew` or `apt get` packages. 

Don't you need HTTP server for that to work? Would `neo` even make one?

@gsmachado can you test #358 on mac and arm?

**Comment by Liaojinghui** [comment]
I dont think neo has ever done that, brew, apt would require NGD to do that.

**Comment by cschuchardt88** [comment]
@gsmachado @Liaojinghui this has been completed by #355 

please close
