### ISSUE TITLE
Inconsistent account naming

### ISSUE THREAD

**Issue by lock9** [neo-project/neo-express#270]
Some commands will depend on the account prefixed with '@' while others don't.

Example:
```neoxp contract run GasToken balanceOf @dev -r```

```neoxp show balance GAS dev ```

Using `@dev` on the show balance command won't work:
```
neoxp show balance GAS @dev                  
System.Exception: @dev account not found.
```

**Comment by cschuchardt88** [comment]
what does contents of your `default.neo-express`? From what i see you may need to add `#` instead of `@`

**Comment by lock9** [comment]
Hi @cschuchardt88,
The problem is that the command doesn't use expect the '@' prefix (or any prefix). 
Try these:
`neoxp contract run GasToken balanceOf @genesis -r`
`neoxp show balance GAS @genesis`

This will work: 
`neoxp show balance GAS genesis`

**Comment by cschuchardt88** [comment]
if you replace the `@` with hash tag (`#`) it should work, from what i see in code.

**Comment by lock9** [comment]
It doesn't:
`System.Exception: #genesis account not found`

**Comment by cschuchardt88** [comment]
It only works for non-genesis. If you name the account, use that name with `#`

**Comment by cschuchardt88** [comment]
See #279 - wrap anything that has a `@` sign, with quotes.

**Comment by lock9** [comment]
Hi @cschuchardt88,
But that is not the point. The point is that account names are inconsistent.  It also doesn't work:
```
neoxp show balances '@genesis'
System.Exception: @genesis account not found.
```

**Comment by cschuchardt88** [comment]
You just going to have to use `#` hashtag.

Using anything else will break old batch files that have been developed by users.
