### ISSUE TITLE
Add support to override existing contracts

### ISSUE THREAD

**Issue by lock9** [neo-project/neo-express#272]
The command `contract deploy` doesn't accept two contracts with the same name. You can use the '--force' flag, which doesn't override the existing contract. When you use the force flag, the user can't invoke their contract anymore (with that name). It throws an error ('2 contracts with the same name').

The primary issue is that we must constantly redeploy the contract during workshops. Today, we request students to rename their contract for every new change in the code - this makes the workshop quite confusing.

Suggestion:
Add support to some 'override' flag when deploying a new contract. This should entirely replace the existing contract in the local network.

**Comment by cschuchardt88** [comment]
You should be creating a checkpoint before each contract deploy, so when you need to redeploy the contract, you have fresh start.

**Comment by lock9** [comment]
Hi @cschuchardt88 ,
Please check this:

>The primary issue is that we must constantly redeploy the contract during workshops. Today, we request students to rename their contract for every new change in the code - this makes the workshop quite confusing.

The point is about not having to do this all the time. It also 'breaks' neo-express after you redeploy a second contract with the same name.

**Comment by cschuchardt88** [comment]
Ok i see. My reason is because this is way it works when you create contract unit tests.
