### ISSUE TITLE
Attempting to invoke an contract results in 'Newtonsoft' error

### ISSUE THREAD

**Issue by robliou** [neo-project/neo-express#275]
Hello DevHawk!

I'm attempting to invoke a deployed contract using the NeoExpress CLI. However, attempting to invoke it using the command:
``neoxp contract invoke test_invoke.json genesis`` 

leads to the error:

``System.InvalidCastException: Cannot cast Newtonsoft.Json.Linq.JObject to Newtonsoft.Json.Linq.JToken.``

I've looked on Discord but don't see any mention of this error from other users.

My ``test_invoke.json`` file is set up as follows:

``
    {
      "contract": {"hash" : "0x5b32709c175bc500d1ff70ebf8746a59c90227a9"},
      "args": [
        "getAmount",
       [

      ]
      ]
}``

I also tried invoking the default ``HelloWorld`` contract (using no arguments) but also get the same error.

Any idea why this error is occuring, and how to solve?

Thanks,

**Comment by lock9** [comment]
Hi @robliou. 
I believe your file is incorrect.
Here is one example:

```
[
    {
        "contract": "token",
        "operation": "transfer",
        "args": [
            "@dev",
            "@genesis",
            1000,
            []
        ]
    },
    {
        "contract": "token",
        "operation": "transfer",
        "args": [
            "@dev",
            "#NFT",
            1000,
            []
        ]
    }
]
```

**Comment by Ashuaidehao** [comment]
Is this resolved?

**Comment by lock9** [comment]
I think it is @Ashuaidehao
