### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by gsmachado** [neo-project/neo-express#280]
As a developer, I would like to change something in the code and run unit tests to check if I didn't break something essential.

(maybe, due to the lack of dotnet knowledge, I could have overlooked where the unit tests are -- in this case, please instruct me and close this issue 🙏 )

@devhawk @JohndeVadoss @steven1227

**Comment by cschuchardt88** [comment]
Neo-express repo use [BlockchainToolkitLibrary](https://github.com/N3developertoolkit/neo-blockchaintoolkit-library) thats where all the tests are

**Comment by cschuchardt88** [comment]
@gsmachado https://github.com/neo-project/neo-express/tree/master/test

@Liaojinghui close
