### ISSUE TITLE
Policy sync issue in batch command

### ISSUE THREAD

**Issue by EdgeDLT** [neo-project/neo-express#281]
I've been testing the `neo-devpack-ts` and tried to enhance the NEP17 sample's batch file with a `policy sync` step, in order to do some basic GAS consumption comparisons with MainNet values. Adding this line to the start of the `express.batch` file and running `neoxp batch express.batch` results in the error `McMaster.Extensions.CommandLineUtils.UnrecognizedCommandParsingException: Unrecognized command or argument 'sync'`.

While troubleshooting, I noticed some other oddities. For example, in this sample repo, `policy get` gives `System.Exception: Cannot call this method with the flag ReadOnly.` If I move to a fresh directory and `neoxp create`, using `policy get` gives the expected result. I'd chalk it up to an Express version difference (`v3.5.20`), but in the new instance I have the same issue with `batch`. 

My process:

```neoxp create
neoxp policy get -r mainnet --json > policy.json
neoxp policy sync policy.json genesis
neoxp policy get
```

I get the expected result:

```
GasPerBlock: 500000000 (5 GAS)
MinimumDeploymentFee: 1000000000 (10 GAS)
CandidateRegistrationFee: 100000000000 (1000 GAS)
OracleRequestFee: 10000000 (0.1 GAS)
NetworkFeePerByte: 100 (0.000001 GAS)
StorageFeeFactor: 100
ExecutionFeeFactor: 3
```

Repeating these steps but replacing the `sync` step with `batch batch.express`, with the batch file containing only `policy sync policy.json genesis`, I receive the original error noted above.

It's not a blocker for me because I can do everything I want with manual `policy set` steps, but it would be nice to have `sync` work in batches for convenience.

**Comment by devhawk** [comment]
Batch is designed to get your environment to a known state. Since the policy data on a public net can change, it's not allowed during `batch`.

You can download the current policy to a file with `neoxp policy get --json > policy.json` and then sync to the policy.json file

**Comment by devhawk** [comment]
my bad, didn't read the issue closely

**Comment by cschuchardt88** [comment]
This can be closed.

**Comment by lock9** [comment]
Did you test it @cschuchardt88 ?

**Comment by cschuchardt88** [comment]
see https://github.com/neo-project/neo-express/pull/335

**Comment by cschuchardt88** [comment]
Close this its fixed now, I forgot to link it.
