### ISSUE TITLE
What is the location of the folder where the block data is stored

### ISSUE THREAD

**Issue by RichardBelsum** [neo-project/neo-express#283]
What is the location of the folder where the block data is stored

There is a Data_LevelDB_334F454E folder in neo-cli to store block data, where is this folder in neoxp?

**Comment by RichardBelsum** [comment]
C:\Users\[username]\AppData\Local\Neo-Express\blockchain-nodes 
**I found it stored in this location, why is it not stated in your documentation and why is it stored in this folder of mine without my permission**

**Comment by lock9** [comment]
<img width="799" alt="Screenshot 2023-06-16 at 10 19 02" src="https://github.com/neo-project/neo-express/assets/38396062/91b7b448-f25c-45b6-967c-fabc199512b2">

From https://www.xda-developers.com/appdata/

**Comment by chenzhitong** [comment]
Why don't we store it with the .neo-express file? So it's easy to copy between computers.
