### ISSUE TITLE
Contract Invoker isn't passing right data types

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo-express#285]
Im getting null for all scripthashes when invoking "ContractManagement.GetContract". Even tried getting native contracts as well.

**Example and outputs**

```csharp
        public static bool GetContract(UInt160 scriptHash)
        {
            return ContractManagement.GetContract(scriptHash) != null;
        }
```
In terminal
```
neoxp contract invoke  .\invoke-files\Untitled.neo-invoke.json genesis -r
VM State:     HALT
Gas Consumed: 3029790
Result Stack:
  false
```
```
neoxp contract list                                                                                                                                                              pwsh  

OracleContract (0xfe924b7cfe89ddd271abaf7210a80a7e11178758)
RoleManagement (0x49cf4e5378ffcd4dec034fd98a174c5491e395e2)
PolicyContract (0xcc5e4edd9f5f8dba8bb65734541df7a1c081c67b)
GasToken (0xd2a4cff31913016155e38e474a2c06d08be276cf)
NeoToken (0xef4073a0f2b305a38ec4050e4d3d28bc40ea63f5)
LedgerContract (0xda65b600f7124ce6c79950c1772a36403104f2be)
CryptoLib (0x726cb6e0cd8628a1350a611384688911ab75f51b)
StdLib (0xacce6fd80d44e1796aa0c2c625e9e4e0ce39efc0)
ContractManagement (0xfffdc93764dbaddd97c48f252a53ea4643faa3fd)
YourName.helloworldContract (0x60cfec8a2d6f7e4bca8078bb076adc4db9b1e54a) <- my contract
```
Contents of ".\invoke-files\Untitled.neo-invoke.json"
```json
[
  {
    "contract": "YourName.helloworldContract",
    "operation": "getContract",
    "args": [
      "0x60cfec8a2d6f7e4bca8078bb076adc4db9b1e54a"
    ]
  }
]
```

**Comment by tiofufo** [comment]
We can confirm that we are having the same issue. All of our tests have been in a private net using the N3 toolkit.

**Comment by ixje** [comment]
I'm going to bet that this is the same problem as https://github.com/neo-project/neo-debugger/issues/188

Can you try the following? 
```json
[
  {
    "contract": "YourName.helloworldContract",
    "operation": "getContract",
    "args": [
     {"type": "ByteArray","value":"SuWxuU3cage7eIDKS35vLYrsz2A="}
    ]
  }
]
```

**Comment by cschuchardt88** [comment]
@ixje Still having same problem

**_File .\invoke-files\Untitled.neo-invoke.json_**
```json
[
  {
    "contract": "YourName.helloworldContract",
    "operation": "getContract",
    "args": [
     {"type":"ByteArray","value":"SuWxuU3cage7eIDKS35vLYrsz2A="}
    ]
  }
]
```
```
>neoxp contract invoke  .\invoke-files\Untitled.neo-invoke.json genesis -r 
VM State:     HALT
Gas Consumed: 3029790
Result Stack:        
  false
```

**Comment by chenzhitong** [comment]
Close it?

**Comment by lock9** [comment]
![image](https://github.com/neo-project/neo-express/assets/38396062/170881ff-345f-4e4c-89b1-1dbf9ea5bafb)

Jokes aside, thank you for giving Neo Express some attention

**Comment by ixje** [comment]
> Close it?

@Liaojinghui  this should not be closed because the problem still exists. According to the documentation anything starting with `0x` should be encoded as bytearray
<img width="774" alt="Screenshot 2023-11-03 at 08 48 43" src="https://github.com/neo-project/neo-express/assets/6625537/eb6c6dc2-7c93-443d-82be-6c03d69efa09">

and his experience is that it results in `null`, where the expected behaviour should be a script hash. The script hash will be wrong, because the `0x...` data needs to be be reversed, but at the very least it should decode to a `UInt160`, not to `null`.

**Comment by Liaojinghui** [comment]
I need to spend some time to be familiar with this project. before that, just tell me what i can help with my permission.

**Comment by ixje** [comment]
* This document needs to become available somewhere. [NDX-DN12_-_Neo_Express_Invoke_Files.md](https://github.com/neo-project/neo-express/files/13248216/NDX-DN12_-_Neo_Express_Invoke_Files.md)

    It is linked [here](https://github.com/neo-project/neo-express/blob/b78a4b65cc1a467dae35ec362ac696edbf8ddd47/docs/command-reference.md?plain=1#L332) and [here](https://github.com/neo-project/neo-express/blob/b78a4b65cc1a467dae35ec362ac696edbf8ddd47/docs/command-reference.md?plain=1#L376) in the documentation but the link points to a repo on the old NGD enterprise Github account and they made the repo private. So nobody can actually read the documentation on how the invocation works (including invoke files). Then it actually needs to work as described there (which is doesn't) due to the at least the follow issues

   1. The issue we're commenting in and [this issue](https://github.com/neo-project/neo-debugger/issues/188) describe 2 problems with arguments supplied as `0x...` not working as intended. 
   2. Then [this issue](https://github.com/neo-project/neo-debugger/issues/195) reported on the `neo-debugger`repo (but also applies for neo-express as they use the same format) describes an issue with the `@N` prefix not working.

**Comment by cschuchardt88** [comment]
If you need any help @Liaojinghui. I reviewed all code so i see how things come together.

**Comment by ixje** [comment]
> If you need any help @Liaojinghui. I reviewed all code so i see how things come together.

If you're up to it @cschuchardt88 , the most efficient way to me sounds like you fixing the issues and for @Liaojinghui or @chenzhitong to test and merge it.

**Comment by Liaojinghui** [comment]
> If you need any help @Liaojinghui. I reviewed all code so i see how things come together.

I just realized that maintaining this repo is also part of my job, but I still need sometime to read the code. If you already have a solution, I can merge it.

**Comment by cschuchardt88** [comment]
> > If you need any help @Liaojinghui. I reviewed all code so i see how things come together.
> 
> @cschuchardt88 I just realized that maintaining this repo is also part of my job, but I still need some time to read the code. If you already have a solution, I can merge it.

All functionally is in [BlockchainToolkitLibrary](https://github.com/N3developertoolkit/neo-blockchaintoolkit-library)

**Comment by cschuchardt88** [comment]
I have linked where the problem is to this issue.

**Comment by ixje** [comment]
> looks like the correct way would be a # not @?

Thanks for linking the parser code. Here are my thoughts

* It looks like using `#` as prefix to indicate the remainder is a UInt160 or UInt256 hash in string representation is not documented at all. This `"args": ["#0x60cfec8a2d6f7e4bca8078bb076adc4db9b1e54a"]` works correctly to translate to a UInt160 on the contract side. This needs to be added to the documentation
* The prefix `@` to indicate the remainder is a NEO address now seems to work correctly and is documented correctly. For example this translates to the same script hash as above `"args": ["@NSjzMPNcRkGKTXF4m7r33wGJwgUbMFJQXU"]`
* [this issue](https://github.com/neo-project/neo-debugger/issues/188) I mentioned no longer seems to be valid. I guess it was silently fixed?

**Comment by cschuchardt88** [comment]
> * [this issue](https://github.com/neo-project/neo-debugger/issues/188) I mentioned no longer seems to be valid. I guess it was silently fixed?

Only other thing it could of been, is from the `neo` core.
Whats the default behavior for:
```csharp
return new ContractParameter(ContractParameterType.String) { Value = value };
```

**Comment by cschuchardt88** [comment]
Documentation needed to be updated, Problem fixed.
