### ISSUE TITLE
NeoExpressBatchFile: Doesn't remove file on clean (Visual Studio)

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo-express#287]
On **Clean** event in Visual Studio `neoxp` doesnt remove file `setup.batch.neoxp.touch` for batching. `neoxp` should remove that file from the `obj` directory. So `neoxp` redeploys the batch file `setup.batch` in this case. But really the file in property `NeoExpressBatchFile` in the projects `.csproj` file.

```xml
<NeoExpressBatchFile>.\setup.batch</NeoExpressBatchFile>
```

Also you shouldn't have to go find the file. New people won't know what to do or the reason why this is happening. i.e. deploy contract; why their contract isn't being updated.

**Comment by cschuchardt88** [comment]
Workaround

```xml
<Target Name="ExecuteRemoveNeoExpressTouchFileAndCheckpointFile" BeforeTargets="Clean">
    <PropertyGroup>
      <TestNeoExpressTouchFile>$([MSBuild]::NormalizePath($(IntermediateOutputPath), '$(NeoExpressBatchFile).neoxp.touch'))</TestNeoExpressTouchFile>
      <TestNeoExpressCheckpointFile>.\bin\checkpoints\contract-deployed.neoxp-checkpoint</TestNeoExpressCheckpointFile>
    </PropertyGroup>
    <Delete Files="$(TestNeoExpressTouchFile);$(TestNeoExpressCheckpointFile)" />
  </Target>
```

**Comment by cschuchardt88** [comment]
@Ashuaidehao can we move this repo [neo-test](https://github.com/N3developertoolkit/neo-test) please, it very useful and its comes in [neo3-visual-tracker](https://github.com/N3developertoolkit/neo3-visual-tracker)

**Comment by Ashuaidehao** [comment]
> @Ashuaidehao can we move this repo [neo-test](https://github.com/N3developertoolkit/neo-test) to here please, it very useful and its comes in [neo3-visual-tracker](https://github.com/N3developertoolkit/neo3-visual-tracker)
> 
> I will maintain here

I'm not familiar very with that project, but I have no objection to your proposal since it has reference to bctk.

**Comment by cschuchardt88** [comment]
@Liaojinghui @shargon is that ok

**Comment by Liaojinghui** [comment]
> neo-test

Yes you can.

**Comment by cschuchardt88** [comment]
> > neo-test
> 
> Yes you can.

@Ashuaidehao can you move it now?

**Comment by Ashuaidehao** [comment]
> > > neo-test
> > 
> > 
> > Yes you can.
> 
> @Ashuaidehao can you move it now?

OK.

**Comment by Ashuaidehao** [comment]
After careful investigation, I find about there are 4 nuget packages maintained in [neo-test](https://github.com/N3developertoolkit/neo-test), and it already has quite pefect github workflows. So I prefer to fork it into `neo-project` more than moving its codes, since merge 4 more packages workflows(test\pack\release) into here would make `neo-express` workflows more complicated and difficult to maintain.  
As an alternative option, I think we can try to combine `neo-test` nuget packages into one(or two)  first and then move here.
What do you think? @Liaojinghui @cschuchardt88

**Comment by Liaojinghui** [comment]
We can add filer to the path

**Comment by cschuchardt88** [comment]
It should be that hard? All current workflows use the solution file, Not release and publish would need to be updated because they use project files but what shouldn't be to hard. 

How about if you manage to get the project in this repo solution files and building. I than can update the workflows? We are in the process of updating anyways. #356  #358

**Comment by Ashuaidehao** [comment]
> It shouldn't be that hard? All current workflows use the solution file, Release and publish would need to be updated because they use project files but that shouldn't be to hard.

Do I need merge these new projects into "[neo-express.sln](https://github.com/neo-project/neo-express/blob/master/neo-express.sln)" or just create a new sln file?

**Comment by cschuchardt88** [comment]
@Ashuaidehao i would merge them, and have one solution.

**Comment by Ashuaidehao** [comment]
> @Ashuaidehao i would merge them, and have one solution.

Sure, I'll copy these projects here.

**Comment by cschuchardt88** [comment]
The vision that @Ashuaidehao merged into this repo as a fix for this issue.
