### ISSUE TITLE
quickstart.md needs to be updated

### ISSUE THREAD

**Issue by chenzhitong** [neo-project/neo-express#292]
[Quickstart.md](https://github.com/neo-project/neo-express/blob/master/docs/quickstart.md) is four years old and needs to be updated! For example, the .net core version is still 2.2 in this document

**Comment by ixje** [comment]
How about making the main `quickstart.md` just about NEO 3 and put the NEO 2 info into a separate document which can be linked to in the main document somewhere at the start with a message "you can find the NEO2 version of this document here".

**Comment by steven1227** [comment]
> How about making the main `quickstart.md` just about NEO 3 and put the NEO 2 info into a separate document which can be linked to in the main document somewhere at the start with a message "you can find the NEO2 version of this document here".

Agree

**Comment by cschuchardt88** [comment]
@Celia18305 Are you able to do this issue?
