### ISSUE TITLE
Add basic regression tests to the pack and release workflows

### ISSUE THREAD

**Issue by lock9** [neo-project/neo-express#294]
Problem: 
We need to make sure Neo Express can run successfully after being built. 

Proposed Solution:  
- Create a test that ensures Neo Express can start the network and make a GAS or NEO transfer.
- Run tests in the build process

Related:
https://github.com/neo-project/neo-express/issues/280

**Comment by cschuchardt88** [comment]
That is all done in [neo-blockchaintoolkit-library](https://github.com/N3developertoolkit/neo-blockchaintoolkit-library) `neo-express` is a proxy/wrapper for that library. `neo-blockchaintoolkit-library` is the neo-express

**Comment by lock9** [comment]
Hello @cschuchardt88,
The regression tests are going to ensure that we are generating working builds. Some problems can only be found after it has been compiled. Check this comment here: https://github.com/neo-project/neo-express/issues/268#issuecomment-1792042838

**Comment by cschuchardt88** [comment]
I believe that has to do with the depends with neo core.

**Comment by cschuchardt88** [comment]
@lock9 check #354 please, Check to make sure it meets requirements.

**Comment by lock9** [comment]
Thank you @cschuchardt88.
That is exactly what I was expecting 👍
