### ISSUE TITLE
Create issue template

### ISSUE THREAD

**Issue by lock9** [neo-project/neo-express#295]
Problem: 
We don't have an issue template in this repository. Issue templates make bug reporting/creating new tasks more efficient.

Proposed Solution: 
Create an issue template similar to what we have in other Neo repositories.

**Comment by cschuchardt88** [comment]
Yes if someone could add this that would be nice. Labels would be nice too and having access to add them to issues is nice too.

**Comment by cschuchardt88** [comment]
@Liaojinghui any word on this? No, rush.

**Comment by Liaojinghui** [comment]
> @Liaojinghui any word on this? No, rush.

I can not create pr for this repo, that will make me not able to merge it.

---
name: Issue Template
about: Template for creating issues in neo-project/neo-express repository
title: '[Issue Type]: Brief Description'
labels: ''
assignees: ''

---

## Issue Type


## Description


## Reproduction Steps


## Expected Behavior


## Actual Behavior


## Version Information
- Neo-Express Version: 
- NEO Blockchain Version: 
- Operating System: 

## Additional Context

**Comment by cschuchardt88** [comment]
@Liaojinghui  ill do it

**Comment by cschuchardt88** [comment]
this can be closed now

**Comment by lock9** [comment]
I didn't have a chance to check the template. I saw that it was just copied from some other place... there was no analysis - literally.

**Comment by Liaojinghui** [comment]
> I didn't have a chance to check the template. I saw that it was just copied from some other place... there was no analysis - literally.

We can create another pr to update the template, since it is not code logic related.

**Comment by lock9** [comment]
I know, but now it's twice the work, you know? We would have better results if we had planned it. The current template doesn't make much sense to us :(

I agree that we can create another PR. Let's fix it with https://github.com/neo-project/neo/issues/2975 instead.

**Comment by Liaojinghui** [comment]
> I agree that we can create another PR. Let's fix it with [neo-project/neo#2975](https://github.com/neo-project/neo/issues/2975) instead.

My bad,  too many issues in the neo project, I prefer to merge as soon as possible if there is no obvious issues. Next time, i will wait.

**Comment by lock9** [comment]
Something to consider for the development process. I can't complain. There aren't rules about merging.

**Comment by Liaojinghui** [comment]
> Something to consider for the development process. I can't complain. There aren't rules about merging.

I prefer an optimistic way to work on non-critical issues, then fallback when problems are discovered. Expecially when we have tons of issues to fix. The same reason that i prefer to close ancient issues aggresively.  But will wait longer in the future.

**Comment by lock9** [comment]
I understand. I agree with you: we need to reduce the development and release cycle as much as possible. However, in some cases, this may backfire and cause more issues that will take longer to resolve. 
This wasn't the case - it has a very low impact. However, we should have some rules to avoid that in the future. Since the team works on different timezones, it would be nice if we had at least 12 hours for the PR to be merged. Maybe 12 hours or 2 approvals?
I think this will make the process fast enough.

In this case, rhe PR, approval and merge happened in less than one hour. I was awake but didn't have time to do anything :(

**Comment by cschuchardt88** [comment]
> I know, but now it's twice the work, you know? We would have better results if we had planned it. The current template doesn't make much sense to us :(
> 
> > **To Reproduce**
> > Steps to reproduce the behavior:
> > 
> > 1. Go to '...'
> > 2. Click on '....'
> > 3. Scroll down to '....'
> > 4. See error
> 
> This is not applicable :(
> 
> I agree that we can create another PR. Let's fix it with [neo-project/neo#2975](https://github.com/neo-project/neo/issues/2975) instead.

how is this bad
