### ISSUE TITLE
Automatically create a user account during 'setup'

### ISSUE THREAD

**Issue by lock9** [neo-project/neo-express#297]
Problem: 
Neo Express uses a multi-sig account as the 'starting account'. This prevents users from importing the private key on other devices (they expect single sig accounts). 

Proposed Solution:
This happens because the genesis account is responsible for running the consensus algorithm. Replacing it for a single sig account is not possible. We should create a new account and transfer part of the NEO and GAS to this new account. We can call it 'dev'.

**Comment by cschuchardt88** [comment]
That's not how it works. The `multi-sig` account is the one running consensus. Genesis is the same the thing; just a `multi-sig` account that holds the initials assets. Don't get it confused with the way a normal node works.

**Comment by lock9** [comment]
Hello @cschuchardt88,
I'm not sure if I understand what you mean 🤔

**Comment by cschuchardt88** [comment]
If you dont want genesis  to be multi-sig i believe if you create (`default.neo-express`) and manually update the consensus address and private key with whatever you want. May only work on single node tho.

**Comment by lock9** [comment]
Ah, ok. This issue is about not having to do all of this. 
Like you said, if we change it, it will only work on 'single node' mode. That is why we should avoid changing the genesis account but create another 'user account' instead

**Comment by cschuchardt88** [comment]
Oh ok, ya that is total do able. Because when you 1st create `default.neo-express` neo-express creates 2 accounts one multi-sig and one normal account. I can't see why not in this process transfer the funds from multi-sig to normal account.

**Comment by lock9** [comment]
Yes, exactly. Just one thing: Here, both accounts are multisig. Are you sure it generates a single sig account?
<img width="617" alt="Screenshot 2023-11-05 at 23 40 22" src="https://github.com/neo-project/neo-express/assets/38396062/b50c0dac-caae-4b06-ad58-2b4868c04d51">

**Comment by lock9** [comment]
I'm a bit confused about the accounts I have here. I think it would be better to create a new account called dev and transfer the funds to it. The 'node1' account is showing as both single sig as multisig. This may lead to confusion
<img width="607" alt="Screenshot 2023-11-05 at 23 42 59" src="https://github.com/neo-project/neo-express/assets/38396062/f55a81cc-4729-4e32-9373-6a391c1a16e5">

**Comment by cschuchardt88** [comment]
You are correct. genesis is the same account as bottom one on `node1`. It's just displayed this way to give mutli-sig account a name. `Default` is the dev wallet.

**Comment by cschuchardt88** [comment]
Have you thought about using `batch` file to do transfers? Really from what I see with `neo-express` is it should be used only for unit testing contracts. Have you also tried creating a unit test for your contracts?

**Comment by Ashuaidehao** [comment]
> Ah, ok. This issue is about not having to do all of this. Like you said, if we change it, it will only work on 'single node' mode. That is why we should avoid changing the genesis account but create another 'user account' instead. It's not that I don't want the genesis to be multisig. I want users to be able to import the developer 'account' in other applications. This is not possible today :(

In the next release version, you can save and use these batch commands to init your private-net:

```
neoxp create
neoxp wallet create --private-key=****YourPrivateKey**** dev
neoxp transfer all neo genesis dev
neoxp transfer all gas genesis dev

```

I think it can fits your needs now.

**Comment by lock9** [comment]
Using manual steps and automation will work. We will add this logic to our extension. However, I can tell from experience that it would be easier for users if they had at least two accounts with GAS.

>neoxp transfer all neo genesis dev
>neoxp transfer all gas genesis dev

This is not an option since it would leave one account without GAS, making it unusable. Transferring one million could be enough.

**Comment by cschuchardt88** [comment]
>In the next release version, you can save and use these batch commands to init your private-net:

Where is this at? I don't see it.

>However, I can tell from experience that it would be easier for users if they had at least two accounts with GAS.

You have to type all the command anyways, right? So what's the problem with typing them once in a batch file?

**Comment by lock9** [comment]
There are two improvements that I want to achieve with this:

First: Make the default account a singlesig account. This is because the current genesis address is a multisig address. If the user tries to import this private key on their devices, it won't work (the account won't have any NEO or GAS).

Second: We need test accounts—at least two. Most applications will work using a 'from <> to' logic. NEP-17 and NEP-11, for example, depend on two accounts to make tests. Without two accounts, the user can only send the tokens to himself/herself. If we provide them with two accounts by default, the first experience could be improved. 

We should create two accounts for the user (like dev1 and dev2 or "Alice" and "Bob"). We should send some of the GAS to both these accounts. This way, the user can use them without going through lengthy steps like creating new accounts and sending the GAS to them. They could also import these accounts into other wallets, allowing us to expand the dev user experience to reach the wallets, increasing downloads.

**Comment by Ashuaidehao** [comment]
> > In the next release version, you can save and use these batch commands to init your private-net:
> 
> Where is this at? I don't see it.
> 
Wait https://github.com/neo-project/neo-express/pull/306 for next production release.

**Comment by cschuchardt88** [comment]
Batch file commands only uses. 

```csharp
[Subcommand(typeof(Checkpoint), typeof(Contract), typeof(FastForward), typeof(Oracle), typeof(Policy), typeof(Transfer))]
```

I don't see wallet. We need to add more or if not all current commands to batch file.

**Comment by cschuchardt88** [comment]
I didn't read it closely.

This can be Closed; fixed with PR #306

**Comment by lock9** [comment]
🤔 
I'm confused. How are these issues related? 
Also, is neo-express always creating accounts using the same private key? I've missed #248  and I don't agree with it at all 😂 

How is the user going to use this account on testnet? (I'm confused, I don't know how these issues relate)

**Comment by cschuchardt88** [comment]
You can specify the private key now. For that dev account that it generates. So the private key you provide can be imported in testnet or mainnet or vice versa.

**Comment by lock9** [comment]
@cschuchardt88 do you mean 'importing a private key'? I'm sorry, I'm having some trouble to understand what that PR changed and how it related to this one here

**Comment by cschuchardt88** [comment]
unless you want WIF format?

**Comment by cschuchardt88** [comment]
>This <ins>prevents users from importing the private key</ins> on other devices

Now you can provide this key!

>Replacing it for a single sig account is not possible

Correct, But you can make the multi-sig address by using that private key you provided. It's only signed with one private key.
