### ISSUE TITLE
Documentation still has errors and needs improvement

### ISSUE THREAD

**Issue by chenzhitong** [neo-project/neo-express#299]
Documentation still has errors and needs improvement

- [x] `contract download`: Need to add
- [x] There are 10+ methods that need to be added to "Usage", e.g. neoxp show balance
- [x] `neoxp contract run`: <Arguments> is options not required
- [x] `neoxp export`: Additional clarification of the location and filename of the exported file is required
- [x] `neoxp wallet delete`: You must specify force to delete a privatenet wallet.
- [x] `neoxp show`: It should be split into multiple commands, e.g. neoxp show balance, neoxp show block...
- [x] `neoxp transfer`: Cannot send all gas, need to explain why in the documentation
- [x] Some link is 404 like [invocation file](https://github.com/ngdenterprise/design-notes/blob/master/NDX-DN12%20-%20Neo%20Express%20Invoke%20Files.md)
- [x] The introduction of the `invocation file` needs to be supplemented with a description of `@` `#` `file://`.
- [x] New "Installation guide" after https://github.com/neo-project/neo-express/issues/362
- [x] `transfernft` `show nft` Need to add after https://github.com/neo-project/neo-express/pull/391
- [x] `candidate` commands need to add after  https://github.com/neo-project/neo-express/pull/402
- [x] `execute` command need to add after  https://github.com/neo-project/neo-express/pull/392
- [x] `contract validate` command need to add https://github.com/neo-project/neo-express/pull/317
- [x] `neoxp batch` Needs to be supplemented, such as `transfernft`, [refer](https://github.com/neo-project/neo-express/blob/master/src/neoxp/Commands/BatchCommand.BatchFileCommands.cs)
- [x] We also need a new [README.md](https://github.com/neo-project/neo-express/blob/master/readme.md) https://github.com/neo-project/neo-express/issues/310

**Comment by lock9** [comment]
Hi @chenzhitong ,
Before we update the documentation, let's try to think if the features make sense themselves. We had a similar issue in the past. In fact, we already started rewriting all the Neo Express docs. The problem is that we need to change the behavior of the tool. Documenting it as it is may lead to confusion in the future. 

Example: https://linkd.academy/en-us/library/neo-blockchain-tools/neo-express/intalling-neo-express/

It was only when we started testing it that we realized something very important: We shouldn't distribute it using 'dotnet tools'. 
I wish to avoid having the same issue here.

**Comment by chenzhitong** [comment]
I found that parameters starting with `@` are converted to `wallet name` and parameters starting with `#` are converted to `UInt160`, so if the parameter type is a string and starts with `#` or `@`, won't it do an incorrect conversion.

```json
[
  {
    "contract": "0x0fe292acdc820abc4bd106abf03a0fab058d7bf ",
    "operation": "sendMessage",
    "args": [ "@Alice How are you!" ]
  }
]
```

**Comment by cschuchardt88** [comment]
See https://github.com/neo-project/neo-express/issues/285#issuecomment-1793502790

**Comment by chenzhitong** [comment]
> I found that parameters starting with `@` are converted to `wallet name` and parameters starting with `#` are converted to `UInt160`, so if the parameter type is a string and starts with `#` or `@`, won't it do an incorrect conversion.
> 
> ```json
> {
>   "contract": "0x0fe292acdc820abc4bd106abf03a0fab058d7bf ",
>   "operation": "sendMessage",
>   "args": [ "@Alice How are you!" ]
> }
> ```

Test passed, no problems here. If it cannot be converted, it will be treated as a string.

**Comment by cschuchardt88** [comment]
You can also use `file://` as an argument for contract, that get converted to base64 string.

**Comment by Liaojinghui** [comment]
Any update to chis checklist?

**Comment by chenzhitong** [comment]
> Any update to chis checklist?

I've just updated some of them.

**Comment by cschuchardt88** [comment]
Resolved
