### ISSUE TITLE
Need a new preview package source

### ISSUE THREAD

**Issue by Ashuaidehao** [neo-project/neo-express#319]
We have an old preview package source feeds at [Azure](https://pkgs.dev.azure.com/ngdenterprise/Build/_packaging/public/nuget/v3/index.json) , but it seems won't be maintained.
Now we change it into [Github package](https://github.com/orgs/neo-project/packages?repo_name=neo-express), but it was set to `private`, no one except neo-project members can pull packages from here.
I think it's time to find a new public place to store the preview packages.

**Comment by Liaojinghui** [comment]
@shargon, do you have the right to make it public?

**Comment by shargon** [comment]
> @shargon, do you have the permission to make it public?

Yes

**Comment by cschuchardt88** [comment]
Yes public would be nice, cause people like me that are not a member, need to access it.

**Comment by Ashuaidehao** [comment]
Should we move to [myget](https://www.myget.org/F/neo/api/v2/package) like other neo-projects?

**Comment by cschuchardt88** [comment]
I would say move everything, but let's ask @Liaojinghui

**Comment by Liaojinghui** [comment]
> I would say move everything, but let's ask @Liaojinghui

https://github.com/neo-project/neo-express/issues/367

**Comment by shargon** [comment]
@neo-project/ngd-seattle won't still maintaining neo-express?

**Comment by cschuchardt88** [comment]
@Ashuaidehao @Liaojinghui 
Can this be closed now? #355 added new source to myget. But we are waiting on the secret to be added.

**Comment by Ashuaidehao** [comment]
OK.
