### ISSUE TITLE
Add `contract` unit tests project to neoxp

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo-express#322]
Lets not forget that neoexp works in unit tests for creating a `contract` unit test. We should add a command to the cli to create one. Or else people won't know.

Workaround is to use my `dotnet-new` templates i created that does this.

you can install like so; to get the template if needed

```
dotnet new install NeoEvents.SmartContract.Templates
dotnet new neosmartcontracttest -o TestProject
cd TestProject
dotnet tool restore
dotnet build
```

**Comment by chenzhitong** [comment]
<img width="904" alt="image" src="https://github.com/neo-project/neo-express/assets/6295602/0a61c2fb-8ae5-4dd2-8bbf-1e3883522239">

What is the reason for this error?

**Comment by chenzhitong** [comment]
```
dotnet tool restore
dotnet neoxp create --force
```
After running this command, I can compile successfully

```
PS D:\1Code\chen\sendMessage\TestProject\bin\Debug\net7.0> dotnet neoxp create
Run "dotnet tool restore" to make the "neoxp" command available.
PS D:\1Code\chen\sendMessage\TestProject\bin\Debug\net7.0> dotnet tool restore
Tool "neo.compiler.csharp" (version "3.6.0") has been restored. Available commands: nccs
Tool "neo.express" (version "3.6.17") has been restored. Available commands: neoxp

Restore successful.
PS D:\1Code\chen\sendMessage\TestProject\bin\Debug\net7.0> dotnet neoxp create
System.Exception: You must specify --force to overwrite an existing file
PS D:\1Code\chen\sendMessage\TestProject\bin\Debug\net7.0> dotnet neoxp create --force
Created 1 node privatenet at D:\1Code\chen\sendMessage\TestProject\bin\Debug\net7.0\default.neo-express
     Note: The private keys for the accounts in this file are *not* encrypted.
           Do not use these accounts on MainNet or in any other system where security is a concern.
PS D:\1Code\chen\sendMessage\TestProject\bin\Debug\net7.0>
```

But when I run the unit test, I get another error again
<img width="818" alt="image" src="https://github.com/neo-project/neo-express/assets/6295602/9e51724c-2d7e-4822-a60e-83fcaabef6e3">

**Comment by cschuchardt88** [comment]
It's a template for my basic contract. you will have to remove it/change it or use _see below_ to setup the unit test. I thought it would be pretty self-explanatory.
```
dotnet new neosmartcontract -o MyContract
```
See readme at https://github.com/cschuchardt88/neo-templates

**Comment by cschuchardt88** [comment]
This will be added to `neo3-visual-tracker` sample workspaces. Once this gets merge #376.

**Comment by cschuchardt88** [comment]
yes
