### ISSUE TITLE
Repo Tags on Releases

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo-express#334]
Can we add repo tags when new releases are released. I don't see any 3.6.0+ tags. Would be much easier to track changes from different versions.

**Comment by cschuchardt88** [comment]
We should also think about deleting the branches that we are not using and `tag` the releases then delete them?

**Comment by Liaojinghui** [comment]
only if we have the permission to do so.

**Comment by Ashuaidehao** [comment]
Need someone run https://github.com/neo-project/neo-express/actions/workflows/release.yml  on branch`release/3.6`, it will auto tag and release.

**Comment by Ashuaidehao** [comment]
Close?
