### ISSUE TITLE
Github actions commands will deprecate

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo-express#344]
Some of our Github actions have deprecated commands in them.

Can someone look into

- The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

I don't know much about yml files

**Comment by Liaojinghui** [comment]
I did not find any command used in this repo will deprecate.

**Comment by cschuchardt88** [comment]
I guess it's `GitVersioning`
![image](https://github.com/neo-project/neo-express/assets/8141309/dd79659c-4d3f-46d5-a94c-29a0efacaa33)
