### ISSUE TITLE
Update the github workflow to produce and distribute Neo Express as a standalone application

### ISSUE THREAD

**Issue by lock9** [neo-project/neo-express#355]
**Is your feature request related to a problem? Please describe.**
We need to ship the neo-express executable. The current workflow doesn't generate or publish the executables. 

Related to #268 

**Describe the solution you'd like**
Update the workflow file to generate and publish the executables here on GitHub

**Additional context**
@cschuchardt88 seems experienced enough to deal with this, so I suggest he works on it

**Comment by cschuchardt88** [comment]
I got things working! 😃 Now that it's a single file you can't pack it. So what you want me to do with the file?

**Comment by cschuchardt88** [comment]
Oh i see executables only .... duh!

**Comment by cschuchardt88** [comment]
@lock9 do you want to check out #358
