### ISSUE TITLE
New Storage Engine

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo-express#359]
Currently we can't make builds for `win-x86`. Reason for this is `rocksdb` doesn't have support.
```
RocksDbSharp.RocksDbSharpException: Rocksdb on windows is not supported for 32 bit applications
```

Yes one can argue the fact that they don't even make `x86` CPUs anymore. Even though `x64` does support `x86` opcodes.

We should build out a new storage? I would recommend using [FasterDb](https://github.com/microsoft/FASTER) it's built in `C#` and microsoft owns it. I have used it before it is pretty faster and very easy to use.

This way we can ensure that `dotnet` standalone executables work correctly for any type of CPU in the future.

**Comment by superboyiii** [comment]
Let x86 go. But I have great interest in `how's the performance among https://github.com/microsoft/FASTER, leveldb and rocksdb`. 
Could you make a comparison on that. If it performs much better, why not? Maybe can apply on neo-cli as well. We have a big issue from LevelDB when Data is hyper big on Legacy mainnet, but Google Team can't solve it: https://github.com/google/leveldb/pull/917
https://github.com/google/leveldb/issues/299
![1700816100972](https://github.com/neo-project/neo-express/assets/38493437/f196609d-890c-43e8-aded-cb3ebaac6665)

**Comment by cschuchardt88** [comment]
`neo-express` doesn't really use `IStore` much (`ONLY` online mode). It uses a custom storage provider with custom `IStore`. This `Fasterdb` can't work as a plugin to slow at syncing because of no seek functionally.

You havent seen my post
- https://github.com/neo-project/neo-modules/issues/155#issuecomment-1705727557
- https://github.com/neo-project/neo-modules/issues/155
- https://github.com/microsoft/FASTER/issues/811
- https://github.com/microsoft/FASTER/issues/870

**Comment by cschuchardt88** [comment]
For `neo-express` `fasterdb` would be a candidate for the node. Reason being even after slowest of syncing entire blockchain; is that we do not import blocks, we won't have that problem. Faster opens 30GB instantly. You can network it together to other `fasterdb` servers (but we don't need this for `neo-express`). However it would be nice if `neo-cli` had `fasterdb` then we could network together and debug/develop on it from `neo-express`.
