### ISSUE TITLE
Add Standalone Packages to...

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo-express#362]
We should open the options for `neo-express` with soon to be standalone packages with #358.
The reason for doing this will allow users to use the app without installing dotnet. Also random searches in these repos may bring new users to the platform after seeing the `neo-express` in action.

### Repos

**Windows Package Manager (winget)**
Setup and [Submit packages](https://learn.microsoft.com/en-us/windows/package-manager/package/). After you create the initial request. I can setup `github` action workflow to deploy new releases.

**apt-get**
Can use github repo for this [Setup](https://wiki.debian.org/DebianRepository/SetupWithReprepro).

**dotnet tool**
we already use this method.

**neo.org/downloads.html**
Have a download page for `neo-express`. This would be a big benefit seeing how no one knows about this app. Let alone where or how to download it.

**brew**
I don't know how

@shargon @Liaojinghui

I would like to know if any of this is possible with the `neo-project`. What the process of getting all this setup? Cause we will need a new hosting repo for `apt-get`, I'm pretty sure `brew` and any others. Maybe `nccs`, `neo-cli` will follow in suite?

**Comment by Liaojinghui** [comment]
This should be handled by NGD. @steven1227 @Ashuaidehao @superboyiii

**Comment by chenzhitong** [comment]
If a standalone packages is created, I can add a link to it here https://neo.org/neogas#wallets

**Comment by cschuchardt88** [comment]
@chenzhitong #358 is in the process of getting approved for images.

**Comment by cschuchardt88** [comment]
well #358 is now live. And word on the future for images on neo.org @chenzhitong ?

I would really like to add to `winget`. It would have to be this repo to do the initial PR to `winget` to get the package started

**Comment by chenzhitong** [comment]
Can you write a profile of neo-express, describing what kind of wallet it is.
@cschuchardt88 
And what's the download page, GitHub Release? There's no release file to download yet!

**Comment by cschuchardt88** [comment]
@Liaojinghui when is a release coming out? so we can get a download. 

@chenzhitong its not a wallet, its a developer node, put it here https://neo.org/dev#tooling

**Comment by chenzhitong** [comment]
We need a logo for neo-express

**Comment by cschuchardt88** [comment]
![neo-express-icon](https://github.com/neo-project/neo-express/assets/8141309/9705e7fa-7d06-44f5-a7e9-2720652b2a76)

**Comment by cschuchardt88** [comment]
@chenzhitong i made that, but currently i added `neo-cli` icon to `neo-express` but we can use the one above

**Comment by Liaojinghui** [comment]
@cschuchardt88 maybe ask ngd for that. I dont know if NGD has some rules to make logos. @steven1227

**Comment by steven1227** [comment]
We have no rules. I like this logo actually ~

**Comment by chenzhitong** [comment]
Done, text description from readme.md 
<img width="380" alt="image" src="https://github.com/neo-project/neo-express/assets/6295602/7d4a9f70-f119-4ba7-abc6-c791049b62a0">

**Comment by chenzhitong** [comment]
![neo-express](https://github.com/neo-project/neo-express/assets/6295602/7a71231e-fefc-4662-97bc-88c221b95923)
Fixed logo edge jaggedness

**Comment by Liaojinghui** [comment]
close as finished.

**Comment by cschuchardt88** [comment]
@Liaojinghui we still need standalone packages release?

**Comment by Liaojinghui** [comment]
> @Liaojinghui we still need standalone packages release?

@steven1227 this standalone packages release thing can only be handled by NGD.

**Comment by steven1227** [comment]
winget only works for windows I think. We should think about all platforms

**Comment by cschuchardt88** [comment]
I have a workflow for building debian packages. Which will install all required dependencies.

**Comment by cschuchardt88** [comment]
> winget only works for windows I think. We should think about all platforms

Each OS has to be done one at a time.

**Comment by gsmachado** [comment]
Yes, I'm working on the `brew` and `apt-get` repositories. I will release something soon. 😄
