### ISSUE TITLE
Add Execute script command

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo-express#365]
**Is your feature request related to a problem? Please describe.**
Allowing script from a file/hex/base64 to be executed. Allow users to test their only scripts. We shouldn't limit `neo-express` or have them use something else. A testing tools should be able to do all the things a developer needs for testing.

**Describe the solution you'd like**
Allow users to execute a VM script from a file or hex/base64 string in the terminal. Also be able to validate a script. Would be the same concept as  `neo-go` version. 

Also display its assembly

**Comment by lock9** [comment]
Hi @cschuchardt88,

Why are you not using the issue templates?

**Comment by cschuchardt88** [comment]
@lock9 I was in a rush and i needed a reminder. i was going to update when i came back. So it updated now.

**Comment by lock9** [comment]
Thanks.

I'm not sure if I understand the problem being resolved. I know that neo-go has something like it, but I don't know how it works.

**Comment by cschuchardt88** [comment]
When developing a script in the scripts assembly can be difficult for some developers, this would be a tool to generate c# code for a script or an base64/hex string of the script. We could add other languages too. Also you can test a script to make sure or see its a script assembly.
