### ISSUE TITLE
Github Action: Proposal to Remove File Uploads from Workflow to Conserve GitHub Storage Space

### ISSUE THREAD

**Issue by Liaojinghui** [neo-project/neo-express#367]
**Is your feature request related to a problem? Please describe.**
We've observed that our current GitHub Actions are uploading files to GitHub, accumulating approximately 70MB of data per action run. While these files are automatically deleted after a few days, frequent updates in a short period could rapidly deplete our available GitHub storage before these files are cleared. To prevent this, I suggest removing the file upload logic from our workflows.

However, I'm unsure if anyone relies on these files generated by our GitHub Actions. I'm opening this issue for discussion. If you depend on these files, please let me know in the comments.

**Describe the solution you'd like**
Remove the logic in the workflow that upload files.

**Additional context**
Non

**Comment by cschuchardt88** [comment]
I don't use them and i think i don't have access to it (never tried). Now that we are merging all the repos. I think it's safe to say we don't need them.  

The culprit would be https://github.com/neo-project/neo-express/blob/master/.github/workflows/push.yml we could remove the publish step.

**Comment by Ashuaidehao** [comment]
@Liaojinghui, do you have permission to delete [neo-express preview packages](https://github.com/orgs/neo-project/packages?repo_name=neo-express)? I think these files cost much GitHub storage, too.

**Comment by Liaojinghui** [comment]
> @Liaojinghui, do you have permission to delete [neo-express preview packages](https://github.com/orgs/neo-project/packages?repo_name=neo-express)? I think these files cost much GitHub storage, too.

Already did.

**Comment by roman-khimov** [comment]
Just upload them into NeoFS (with appropriate LIFETIME to autodelete): https://github.com/nspcc-dev/gh-push-to-neofs/

**Comment by Liaojinghui** [comment]
Who is going to pay for the storage?

**Comment by Liaojinghui** [comment]
> Just upload them into NeoFS (with appropriate LIFETIME to autodelete): https://github.com/nspcc-dev/gh-push-to-neofs/

Its free?

**Comment by roman-khimov** [comment]
Got some GAS?

**Comment by Liaojinghui** [comment]
> Got some GAS?

U know how poor I am. Ngd doing this would be complex. So, I would just delete the artifacts.

**Comment by lock9** [comment]
I think we should release it on NeoFS. The GAS could come from the imaginary core developer treasury 😂

**Comment by roman-khimov** [comment]
GAS is not a problem, I think.

**Comment by cschuchardt88** [comment]
@Liaojinghui 
Forgot to link to #373

deployed on development branch

please close as completed?
