### ISSUE TITLE
Create command stopped working (always using the default path)

### ISSUE THREAD

**Issue by lock9** [neo-project/neo-express#369]
**Describe the bug**
The 'create' command in Neo Express is broken, preventing the creation of distinct configuration files in separate project folders. I can't use it anymore.

**To Reproduce**
1. Use `neoxp create` in a folder
2. Use `neoxp create` in second a folder
3. The second command will fail: `System.Exception: You must specify --force to overwrite an existing file`

**Expected behavior**
I should be able to create different Neo Express configuration files. A simple solution would be to accept a '-o' parameter to set the file path. `neoxp create -o .' 

**please complete the following information**
 - Version: Master

**Comment by lock9** [comment]
I was able to fix it using a new parameter

**Comment by cschuchardt88** [comment]
We added #273 you wanted global file so other projects can use the `default.neo-express` file. It defaults to global see #324
