### ISSUE TITLE
New design of express-get-populated-blocks requires O(n) RPC calls to render a single page of blocks in the dev tracker

### ISSUE THREAD

**Issue by djnicholson** [neo-project/neo-express#37]
We initially created the express-get-populated-blocks to avoid having to make O(n) RPC calls when rendering a filtered page of blocks in the dev tracker (where n is the size of the blockchain).

The new design re-introduces this characteristic.  It is 100x faster than it used to be (100 blocks can be checked at once) but still results in an unusable dev tracker UI experience when viewing a blockchain that has mostly unpopulated blocks (this will be common if a developer has left neo-express running generating empty blocks every 15s).

Suggest reverting https://github.com/neo-project/neo-express/pull/36. If we need a more efficient implementation of express-get-populated-blocks, we should maintain a persistent bitset of populated blocks within neo-express and update it as blocks are created.  The dev tracker cannot maintain this data structure as it changes in-between checkpoints.

**Comment by djnicholson** [comment]
Example of poor dev tracker performance when using the new paginated API: https://github.com/neo-project/neo-visual-tracker/tree/populatedblockpagination (to repro view a very large blockchain in the dev tracker and enable the 'populated blocks only' filter)

**Comment by devhawk** [comment]
We aren't fixing this for Neo Legacy. @djnicholson  is this still an issue in Neo N3 devtracker/express?

**Comment by djnicholson** [comment]
N3 DevTracker retrieves 100 blocks at a time and has logic to make sure it will only re-crawl the blockchain if it detects a reset or checkpoint application.  Let's revisit if this becomes an issue in real-world scenarios (may need to increase the page size to be a lot higher than 100 if so).
