### ISSUE TITLE
Why use neo-express instead of neo-cli

### ISSUE THREAD

**Issue by RichardBelsum** [neo-project/neo-express#375]
Why use neo-express instead of neo-cli, I think the private chain built by neo-cli is sufficient for development needs

**Comment by cschuchardt88** [comment]
This is a development node, that does has special debugging feature. 

Some that are included:
- unit testing contracts
- debugging contracts
- vscode extension for developing contracts
- etc ...

Can you explain a little more on what you mean? Have you used `neo-express`? do you develop on `neo-cli`?

**Comment by RichardBelsum** [comment]
I have been using neo-cli to develop smart contracts. After building my privatenet, I used RPC to deploy and invoke the contract, and didn't find anything inconvenient.

**Comment by RichardBelsum** [comment]
Most contract developers use neo-cli, right?

**Comment by Liaojinghui** [comment]
neo express is specifically designed and developed for contract development, test, and debug. While neo-cli is a neo full-node. You can compare express with E-letter chain remix or hardhat.

**Comment by cschuchardt88** [comment]
>Most contract developers use neo-cli, right?

I am unsure on that. After abandonment of `neo-express` and its tools, im sure they did just use `neo-cli`. Now that we are back on the project working hard.

**Comment by cschuchardt88** [comment]
@Liaojinghui 
i have been thinking about, If we made `neo-express` into a `neo-cli` plugin.

**Comment by Liaojinghui** [comment]
In the future, maybe.
