### ISSUE TITLE
When `neo-express run` and `neo-express checkpoint run` fail; don't block waiting for the user to hit 'q'

### ISSUE THREAD

**Issue by djnicholson** [neo-project/neo-express#39]
Right now it is hard to programmatically no whether neo-express started successfully not because the process stays running even when there is an error (it shows a help message and waits for a user to hit 'q')

**Comment by devhawk** [comment]
This appears to be a bug in https://github.com/natemcmaster/CommandLineUtils. Even though I set [UsePagerForHelpText to false](https://github.com/neo-project/neo-express/blob/master/src/neo-express/Program.cs#L36) on program startup, the run command is not respecting that. However, the next release of CommandLineUtils [flips the default to false](https://github.com/natemcmaster/CommandLineUtils/pull/347) so I think this will resolve itself with a package update once the next release of CommandLineUtils is released 

cc @natemcmaster

**Comment by devhawk** [comment]
Nope, turns out it's my bad - just need to set `UsePagerForHelpText` to false *before* calling `UseDefaultConventions`

**Comment by devhawk** [comment]
Neo.Express v1.0.8 w/ this fix published to nuget.org
