### ISSUE TITLE
Fix: Adding env.secret settings

### ISSUE THREAD

**Issue by Jim8y** [neo-project/neo-express#397]
**Is your feature request related to a problem? Please describe.**
This repo requires new or an update to the env.secrets such that we could properly publish new versions.

**Describe the solution you'd like**
The maintainer with permission of updating the repo setting may help us to update the existing sectres or add new secrets.

**Additional context**
None

**Comment by shargon** [comment]
I saw that currently is with "Public repositories" as visibility, it should be accessible to neo-express...

**Comment by cschuchardt88** [comment]
@shargon `error: Missing value for option 'api-key'`

```
dotnet nuget push ./out/Neo.Assertions.*.nupkg --source https://www.myget.org/F/neo/api/v3/index.json --api-key 
  shell: /usr/bin/bash -e {0}
  env:
    CONFIGURATION: Release
    DOTNET_VERSION: 7.0.x
    DOTNET_ROOT: /usr/share/dotnet
    GitAssemblyInformationalVersion: [3](https://github.com/neo-project/neo-express/actions/runs/6999186509/job/19038246339#step:8:3).6.69-preview+61[4](https://github.com/neo-project/neo-express/actions/runs/6999186509/job/19038246339#step:8:4)4[5](https://github.com/neo-project/neo-express/actions/runs/6999186509/job/19038246339#step:8:5)70[6](https://github.com/neo-project/neo-express/actions/runs/6999186509/job/19038246339#step:8:6)[8](https://github.com/neo-project/neo-express/actions/runs/6999186509/job/19038246339#step:8:8)4
    GitBuildVersion: 3.6.6[9](https://github.com/neo-project/neo-express/actions/runs/6999186509/job/19038246339#step:8:9).24900
    GitBuildVersionSimple: 3.6.69
Required argument missing for option: '--api-key'.

Specify --help for a list of available options and commands.
error: Missing value for option 'api-key'
```

**Comment by cschuchardt88** [comment]
I know it was working before. It seems it was removed for this repo or can only run on certain job/step.

**Comment by Liaojinghui** [comment]
@shargon  the grand master, NUGET_TOKEN is expiring in 5 days.

**Comment by Liaojinghui** [comment]
BTW, may you also set pack/pack as  not required, @shargon.

**Comment by Liaojinghui** [comment]
pack job of the pack workflow is set as required. Cant you modify that from the setting?

**Comment by Liaojinghui** [comment]
pack job of the pack workflow is set as required. Cant you modify that from the setting?

**Comment by Liaojinghui** [comment]
pack job of the pack workflow is set as required. Cant you modify that from the setting?

**Comment by cschuchardt88** [comment]
@shargon can we get `pack.yml` workflow not be required anymore please? 
![image](https://github.com/neo-project/neo-express/assets/8141309/aefd927a-5e02-4d6e-a389-2ba36a47d025)

**Comment by cschuchardt88** [comment]
![image](https://github.com/neo-project/neo-express/assets/8141309/438625a5-429a-4c28-9d40-5b5f6d2001df)

**Comment by shargon** [comment]
@Liaojinghui Is deprecated https://docs.github.com/en/actions/using-workflows/required-workflows I think that we must create a ruleset, What does `pack` do?

**Comment by cschuchardt88** [comment]
@shargon currently we removed all logic. But what it did do Is, `pack` nuget packages and `publish` to github. And any PR could do this. So each time you commit on a `PR` it would `publish` to github nuget.

**Comment by shargon** [comment]
I removed the required from:

`release/v*` (Currently applies to 16 branches)
And still be required for `master-2.x` and `master`

**Comment by shargon** [comment]
I see that all is merged to master, so I will do the oposite xD

> I removed the required from:
> 
> `release/v*` (Currently applies to 16 branches) And still be required for `master-2.x` and `master`

**Comment by shargon** [comment]
@Liaojinghui @cschuchardt88 please check it

**Comment by cschuchardt88** [comment]
Looks like its removed. We still have to test `myget` token secrets on pushing to master after #415

![image](https://github.com/neo-project/neo-express/assets/8141309/e1c8a1d9-a537-4289-8848-a9621fd37fd5)

**Comment by shargon** [comment]
> Looks like its removed. We still have to test `myget` token secrets on pushing to master after #415
> 
> ![image](https://private-user-images.githubusercontent.com/8141309/288706207-e1c8a1d9-a537-4289-8848-a9621fd37fd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NTIzNDgsIm5iZiI6MTcwMTk1MjA0OCwicGF0aCI6Ii84MTQxMzA5LzI4ODcwNjIwNy1lMWM4YTFkOS1hNTM3LTQyODktODg0OC1hOTYyMWZkMzdmZDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDdUMTIyNzI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTFiZjQ4MGYzNGM0M2RhMjRiYWM0NmFkODZmODU1NTE2ZGE0ZGM1NDI4OTNlNGI3Yzg2ZWJlZmU3YzhiOTM3NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7pXPEZFaJGbIQA5_jUP5Da7TT1jAq70s--VHGkdccIg)

We have problems with myGet space ... we are trying to deal with it

**Comment by cschuchardt88** [comment]
@shargon 
Yes i see it problem on `neo` repo 
![image](https://github.com/neo-project/neo-express/assets/8141309/a76464bd-1099-466c-8897-a930b7930057)

But the problem has to do with you uploading to many files at once. You have to break the files into different steps when uploading _(each one in each step)_.

**Comment by cschuchardt88** [comment]
@shargon can you figure this out please or @NGDAdmin @superboyiii

**Comment by shargon** [comment]
It takes the organization secret, that is working for neo

**Comment by cschuchardt88** [comment]
> It takes the organization secret, that is working for neo

Ok, I was thinking `my-get`.

**Comment by cschuchardt88** [comment]
Resolved
