### ISSUE TITLE
Upload artifacts into NeoFS

### ISSUE THREAD

**Issue by roman-khimov** [neo-project/neo-express#398]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I see #367, #396 and alike (#404). All those artifacts might be very handy to try/debug/test things.

**Describe the solution you'd like**
Use https://github.com/nspcc-dev/gh-push-to-neofs/ and save everything in NeoFS.

**Comment by Liaojinghui** [comment]
I would love to upload them into NeoFs, but it can only be handled by NGD (@steven1227) since it requires a neo account that is not supposed to be controled by core-dev. But before we have one from NGD, we need to save the space.

**Comment by cschuchardt88** [comment]
UPDATE: Currently we are using caching instead of artifact upload.

**Comment by cschuchardt88** [comment]
Resolved already
