### ISSUE TITLE
Inconsistent versioning

### ISSUE THREAD

**Issue by gsmachado** [neo-project/neo-express#416]
In the pre-releases, we have the version set to, e.g.: `3.6.87-preview-ge9662af55d`
Check this URL: https://github.com/neo-project/neo-express/releases/tag/3.6.87-preview-ge9662af55d

Pay attention that version `3.6.87` is appended with `preview` and then `ge9662af55d` (which, is weird, is like 11 chars, it should be 5 bytes, no?).

But when I run `neoxp --version`, it prints:

`3.6.87-preview+e9662af55`

I was expecting either the pre-release to be `3.6.87-preview+e9662af55` or `neoxp --version` to print `3.6.87-preview-ge9662af55d`. But, not two different things, in any circumstance.

👉 MY SUGGESTION:

Change the version, everywhere, to be: `3.6.87-preview-e9662af55d`.

* `3.6.87` is the version (increments)
* `preview` represents a "preview" version/release
* `e9662af55d` is the hex representation of 5 bytes, 10 chars.

**Comment by gsmachado** [comment]
Just tagging @cschuchardt88 and @Liaojinghui here, to get into the loop.

**Comment by gsmachado** [comment]
awesome! Thanks @cschuchardt88 and @Liaojinghui!

**Comment by Liaojinghui** [comment]
@cschuchardt88 owns all the credits.
