### ISSUE TITLE
Update command not working when the update method uses the 'data' parameter

### ISSUE THREAD

**Issue by lock9** [neo-project/neo-express#419]
**Describe the bug**
We use Neo Express update method in our extension. It works as long as the update method follows this format:
`update(nef: bytes, manifest:str)`

The update method accepts an optional parameter "data". If we use this parameter, Neo express is unable to update the contract
`update(nef: bytes, manifest:str, data: Any)`

**To Reproduce**
1. Create a new contract with an update without the data parameter
2. Deploy the contract
3. Try to update the contract. It should work
4. Add the optional "data" parameter. 
5. Recompile and try to update the contract. It will fail because it won't find the update method.

**Expected behavior**
The update feature should work with and without the data parameter.

**Comment by cschuchardt88** [comment]
This goes the same way if you have `func1(param1, param2)` and update to `func1(param1)`. The reason is because method with 2 params now doesn't exist. In your case standard/non-standard is not to have `data` param on `update` method `bool Update(ByteString nefFile, string manifest)`.
