### ISSUE TITLE
NEP-17 Validation is breaking existing examples

### ISSUE THREAD

**Issue by lock9** [neo-project/neo-express#428]
**Describe the bug**
Neo express is refusing to deploy a NEP-17 contract, arguing that it's not NEP-17 compliant. The problem applies to both our Python and C# examples. We believe that the validation may not be working as expected.

**To Reproduce**
1. Create a NEP-17 example / take one from here: https://gist.github.com/lock9/78aa3b2fc41c44b453b7b9ab82f21be8
2. Compile the contract 
3. Try to deploy the contract
4. See error: ``` 
System.Exception: Coin Contract Contract declares support for NEP-17 standards. However is not NEP-17 compliant. Invalid methods/events.```

**Expected behavior**
We believe it should work. We are having the same issue with our Python NEP-17 contract. We've tried to update the manifest manually to fix differences in parameter names or types, but it didn't work.

**please complete the following information**
 - OS: macOS Ventura
 - Version 3.6.94

**Comment by roman-khimov** [comment]
There should be a better error message, of course (`manifest is not compliant with 'NEP-17': 'balanceOf' method has wrong safe flag: expected true` for example), but have you checked the manifest against NEP-17?

**Comment by cschuchardt88** [comment]
It was a typo in `neo-express` with `transfer` not being `Transfer`

**Comment by lock9** [comment]
>There should be a better error message, of course (manifest is not compliant with 'NEP-17': 'balanceOf' method has wrong safe flag: expected true for example), but have you checked the manifest against NEP-17?

Yes, I did. Two different examples stopped working, which is why I suspected it was a bug (it is). It will be fixed by #430

**Comment by Jim8y** [comment]
fixed by https://github.com/neo-project/neo-express/pull/430
