### ISSUE TITLE
Make NEP validation errors more informative

### ISSUE THREAD

**Issue by lock9** [neo-project/neo-express#429]
**Is your feature request related to a problem? Please describe.**
Neo Express is refusing to deploy our NEP-17 contracts, complaining that they are not NEP-17 compatible.  There may be some problem on our code, but we have no idea where it is. There are multiple validations but only a single error message.

**Describe the solution you'd like**
Neo Express should inform which field is failing validation.

**Additional context**
If possible, the user should be informed of all errors at once instead of returning just the first error that is found.

**Comment by cschuchardt88** [comment]
You can bypass by using `--force`

**Comment by lock9** [comment]
I don't to bypass it, I want to know what the problem is.

**Comment by cschuchardt88** [comment]
@chenzhitong you want to take this one?
