### ISSUE TITLE
NEP-11 Validation is breaking existing examples

### ISSUE THREAD

**Issue by lock9** [neo-project/neo-express#431]
**Describe the bug**
Neo express is refusing to deploy valid NEP-11 contracts.

**To Reproduce**
Try to deploy a valid NEP-11 contract.

**Expected behavior**
It should work.

**Additional context**
- [Incorrect event name](https://github.com/neo-project/neo-express/blob/7b0cef813381ce1f69289ef9cd9e369b84e88655/src/neoxp/Extensions/ContractManifestExtensions.cs#L68C38-L68C38)
- [Incorrect parameter count](https://github.com/neo-project/neo-express/blob/7b0cef813381ce1f69289ef9cd9e369b84e88655/src/neoxp/Extensions/ContractManifestExtensions.cs#L69)

It looks like the code was never tested.

**Comment by cschuchardt88** [comment]
It shows it was tested. Whatever the reason it got changed. It will be fixed now.

https://github.com/neo-project/neo-express/blob/7b0cef813381ce1f69289ef9cd9e369b84e88655/src/neoxp/Extensions/ContractManifestExtensions.cs#L76

**Comment by lock9** [comment]
Then we can say that it was tested, but it never passed the tests 😂 
I think it's better to add some tests to this and other new features. I'm sure it's possible to test it somehow
