### ISSUE TITLE
Allow contract storage modification during download

### ISSUE THREAD

**Issue by EdgeDLT** [neo-project/neo-express#436]
**Is your feature request related to a problem? Please describe.**

`contract download`, which I am using with https://github.com/CityOfZion/cpm, is very convenient when you want to test against MainNet contract state. Especially when the contract has no permissioned methods. But most of the interesting contracts have an `owner` of some kind which can modify its configuration. This means copying MainNet state as-is can leave you somewhat limited for testing.

**Describe the solution you'd like**

Add the ability to overwrite specific storage values when downloading contract state. If I know the contract has an owner key stored at `0x00`, then I want to be able to do `neoxp contract download ... --overwrite 0x00 <myLEscripthash>`. Now I can take control of the contract to configure it as I need. 

This is one use case, maybe the main use case, but perhaps there are others.

**Comment by lock9** [comment]
Hello,

Can you check if this will help you?
https://github.com/neo-project/neo-express/pull/434

It was implemented recently but not released

**Comment by EdgeDLT** [comment]
@lock9 Looks like it will, thanks.
