### ISSUE TITLE
Relative paths not working properly when creating checkpoints

### ISSUE THREAD

**Issue by lock9** [neo-project/neo-express#437]
**Describe the bug**
When we pass relative paths, the command 'checkpoint create' does not create the file in the correct location. Instead of adding the files to our project folder, it puts them in the 'default neo express folder.'

If I run `dotnet neoxp checkpoint create ./checkpoints/contracts-deployed`, the checkpoint is saved on ~/.neoxp/checkpoints/contracts-deployed.  The correct path should be './checkpoints/contracts-deployed'

**To Reproduce**
1. Use 'neoxp checkpoint create ./<folder>/contracts-deployed
2. Look for the file. It won't be there. Instead, it will be on ~/.neoxp/<folder>/contracts-deployed

**Expected behavior**
The file should be placed on  ./<folder>/contracts-deployed (relative path)

**Screenshots**
<img width="346" alt="Screenshot 2024-05-16 at 11 11 33" src="https://github.com/neo-project/neo-express/assets/38396062/eea2963f-6ef6-4083-9f23-06ac8f47b6d2">

**please complete the following information**
 - OS: osx
 - Version 3.6.94

**Additional context**
I think that the problem originated here: https://github.com/neo-project/neo-express/pull/324/files. I'm not 100% sure.

**Comment by cschuchardt88** [comment]
This is by design. However `neo-express` will look for files in the current directory to `read` from. You need to add `fully qualified path`, if you want it somewhere else.
