### ISSUE TITLE
Should Core-devs maintain this repo?

### ISSUE THREAD

**Issue by Jim8y** [neo-project/neo-express#441]
Please vote. 👍 as it should,  👎 as should not.

**Comment by cschuchardt88** [comment]
see https://github.com/neo-project/neo/issues/3238, This will end up replacing `neo-express`.

**Comment by Jim8y** [comment]
@cschuchardt88 you can make this plan, but you should expect this to be finished in 10 years. You like that?

**Comment by cschuchardt88** [comment]
> @cschuchardt88 you can make this plan, but you should expect this to be finished in 10 years. You like that?

Well if no one helps or  merges changes.

**Comment by Jim8y** [comment]
> > @cschuchardt88 you can make this plan, but you should expect this to be finished in 10 years. You like that?
> 
> Well if no one helps or merges changes. Thats what the `new` `cli` is I wanted your help for. It will become that...

You know it will take that long even if with my help. This will be a big task, need to be finished with many many smaller tasks, and each will take a long while to be reviewed and merged. You know how it works.

**Comment by Jim8y** [comment]
Well, just user need it, no one is miantaining it, then should we maintain it or should we just discard it. 

So, please only focus on one thing and dont consider others: should we keep this or should we archive it?

**Comment by lock9** [comment]
It depends on what you call 'maintain'. Do you mean adding new features or keeping it working?
Many people use and depend on this tool. 

We can create a GrantShares proposal if the core developers don't want to maintain it. Since there isn't a replacement, I don't think Neo Express can be abandoned.

**Comment by Jim8y** [comment]
> It depends on what you call 'maintain'. Do you mean adding new features or keeping it working? Many people use and depend on this tool.
> 
> We can create a GrantShares proposal if the core developers don't want to maintain it. Since there isn't a replacement, I don't think Neo Express can be abandoned.

I need to make it very clear who should maintain this repo, otherwise this project is not sustainable.

**Comment by lock9** [comment]
Many projects use Neo express and there isn't a replacement. In fact, the lack of maintenance on this project is one of the biggest bottlenecks in onboarding new developers. Now, who will maintain it? IMO, it should be the core developers or equivalent. 

We (Linkd Academy) can adopt Neo Express. In fact, that would be ideal for everyone, since we are using it with many people and get a lot of feedback about it.  However, that can't be done without resources. Then, if a Grantshares proposal or another type of funding is not possible, core devs will have to maintain it.

**Comment by shargon** [comment]
In my opinion we should maintain it, it's important for the ecosystem

**Comment by cschuchardt88** [comment]
> In my opinion we should maintain it, it's important for the ecosystem

If we do, we need `react` developer for the `vscode` plugin.

**Comment by Jim8y** [comment]
> > In my opinion we should maintain it, it's important for the ecosystem
> 
> If we do, we need `react` developer for the `vscode` plugin.

If we just do what we already know, then we are not just limiting ourself, we are also limiting the neo-core.

**Comment by mialbu** [comment]
Neow3j is dependent on `neo-express` for its test framework. As long as there's no Neo 3.7.4-compatible version of it, we're blocked from releasing parts of our tools.

We'd definitely like to have some clarity on whether `neo-express` will be maintained, OR if the goal is for it to be replaced by something new (https://github.com/neo-project/neo-express/issues/441#issuecomment-2116466255).

Even if the goal will be _not_ to maintain `neo-express` in the long-term, we'll need some short-term solution. Either we'll need some compatibility updates of `neo-express` to get us unblocked or we'll need to change our tools accordingly and reduce/remove the dependency to `neo-express` (which will definitely not happen from one day to another...).

With all that being said, could you guys give me some clarity on the _short-term_ plan for `neo-express`? For example, will someone work on a Neo 3.7.4-compatible release of `neo-express`, and if so, can you provide an ETA for it?

@Jim8y @cschuchardt88 @shargon @roman-khimov

**Comment by cschuchardt88** [comment]
`neo-express` can't be updated until `neo` `3.7.5`. There were changes in `3.7.4` that are blocking us from releasing.

**Comment by ixje** [comment]
I think there are quite a few projects that rely on neo-express for it's `checkpoint` ability. As far as I know there is no alternative to that. 

I'm not so sure about the importance of the VSCode plugin. @lock9 probably has some idea about that or we can do a poll/survey amongst past hackathon participants to get a feel how important it is.

**Comment by Jim8y** [comment]
> I think there are quite a few projects that rely on neo-express for it's `checkpoint` ability. As far as I know there is no alternative to that. 
> 
> 
> 
> I'm not so sure about the importance of the VSCode plugin. @lock9 probably has some idea about that or we can do a poll/survey amongst past hackathon participants to get a feel how important it is.

Decision has being made by voting that this repo will be maintained by core dev and NGD, contributions from communities are also welcome.

**Comment by mialbu** [comment]
> Decision has being made by voting that this repo will be maintained by core dev and NGD, contributions from communities are also welcome.

Can you close this issue then? If it stays open it appears as if it's still under discussion and there's no final decision. 😅
