### ISSUE TITLE
neo express relative path broken

### ISSUE THREAD

**Issue by vincentgeneste** [neo-project/neo-express#444]
there is still an issue with relative path on neo express.

There was an attempt to fix it it seems but it still does not work as intended, and while it was working for a long time it is not anymore: https://github.com/neo-project/neo-express/pull/438

**Issue:**

when running `dotnet neoxp checkpoint create checkpoints/contracts-deployed -f` it actually reads the neo express default file from a temporary file on the computer, and not relative to where the command is run. this can be bypassed locally by adding `-i default.neo-express`.

but when running this into github actions, we can not specify it, thus making github actions brokens for this particular command.

Note: if we pass an absolute path, it works as intended, the issue is only specific to relative paths. (obviously we can not use absolute paths for github actions)

**Comment by Jim8y** [comment]
I will check and fix it.

**Comment by cschuchardt88** [comment]
You add the `-i ${{ github.workspace }}/default.neo-express`. 

`${{ github.workspace }}` in workflow is the absolute path on VM disk to your repo directory

#### Example:
```yml
- name: Test Checkpoint Command (offline) (neoxp)
  run: dotnet neoxp checkpoint create checkpoints/contracts-deployed -f -i ${{ github.workspace }}/default.neo-express
```

**Comment by cschuchardt88** [comment]
Fixed
