### ISSUE TITLE
Endpoint 'getnep11balances' throwing error:     "Value does not fall within the expected range. (Parameter 'obj')"

### ISSUE THREAD

**Issue by lock9** [neo-project/neo-express#452]
**Describe the bug**
The 'getnep11balances' endpoint throws an exception when I try to use it. This doesn't happen on mainnet or testnet nodes.

**To Reproduce**
1. Send a request to the 'getnep11balances' endpoint, passing an address as a parameter
2. Check the response 'error' field. It should be: "Value does not fall within the expected range. (Parameter 'obj')"

**Expected behavior**
It should return the user balance and not an error (even if it's empty). 

**please complete the following information**
 - OS: macOS
 - Version: 3.7.3

**Comment by cschuchardt88** [comment]
This maybe fixed doto a bug in core with `snapshot`.
![image](https://github.com/user-attachments/assets/d568f3f8-90e5-45a3-9bb3-d1ef06d1f89e)
