### ISSUE TITLE
Endpoint 'getnep17balances' throwing error: "Invalid params - One of the identified items was in an invalid format.

### ISSUE THREAD

**Issue by lock9** [neo-project/neo-express#453]
**Describe the bug**
The 'getnep17balances' endpoint throws an exception when I try to use it. This doesn't happen on mainnet or testnet nodes.
Edit: It seems that Neo Express crashed before the error started to appear: 
```
neoxp(29517,0x16b8df000) malloc: Heap corruption detected, free list is damaged at 0x6000006482a0
*** Incorrect guard value: 5120
neoxp(29517,0x16b8df000) malloc: *** set a breakpoint in malloc_error_break to debug
```

**To Reproduce**
1. Send a request to the 'getnep17balances' endpoint, passing an address as a parameter
2. Check the response 'error' field. It should be: "Invalid params - One of the identified items was in an invalid format"

**Expected behavior**
It should return the user balance and not an error (even if it's empty). 

**please complete the following information**
 - OS: macOS
 - Version: 3.7.3

**Comment by cschuchardt88** [comment]
This problem be fixed now doto a bug in core. 
![image](https://github.com/user-attachments/assets/18191495-c47f-4d86-8ba2-84363380bebc)
