### ISSUE TITLE
neoxp hangs forever when executing the batch command

### ISSUE THREAD

**Issue by gsmachado** [neo-project/neo-express#455]
**Describe the bug**

When I execute `neoxp batch -i default -r setup.batch` the process simply hangs forever or it outputs an ugly error (`Segmentation fault (core dumped)`)

Example of a `Segmentation fault`:
![image](https://github.com/user-attachments/assets/275acb6e-f9c3-424b-a96c-010e142916c8)

Below you can find the case that most frequently happens: the neoxp batch command just hangs, forever. Never returns.
![image](https://github.com/user-attachments/assets/f29d669b-102d-48cd-a3c5-7ccc90c51360)

Sometimes, if the `neoxp batch` successfully completes, then, it simply outputs the following error when I start with the command `neoxp run -i default`: `RocksDbSharp.RocksDbException: Corruption: bad WriteBatch Put`.

**To Reproduce**

I can't reproduce the problem 100% of the time, since it might be a timing issue, race condition, or maybe rocksdb handlers are not properly closed. I'm not sure, but it certainly needs some investigation.

HOWEVER, I can provide you with a `setup.batch` and `default.neo-express` files that most likely can reproduce the problem:

Please use the following files:
- [`setup.batch`](https://cdn.axlabs.net/neow3j-files/tmp/setup.batch)
- [`default.neo-express`](https://cdn.axlabs.net/neow3j-files/tmp/default.neo-express)

Place them in a directory and then, within the same dir, run:

`$ neoxp batch -i default -r setup.batch`

Try to execute this command a couple of times in sequence.

**Expected behavior**
The `neoxp batch` command should successfully complete, 100% of the time.

**Info about platform**
 - OS: Linux (with and without docker)
 - Version: Ubuntu 24.04 and 22.04
 - Platform: both arm64 and amd64

**Additional context**

- You might want to check this [comment](https://github.com/facebook/rocksdb/issues/262#issuecomment-1005123065).
- Maybe this problem gets manifested in other commands that I haven't extensively tried yet.

**Comment by gsmachado** [comment]
We highly appreciate the good work put so far in neo-express. However, we rely on this software and need to address this soon. 🙏

**Comment by Jim8y** [comment]
Will check right away

**Comment by cschuchardt88** [comment]
Wasnt able to reproduce 
![image](https://github.com/user-attachments/assets/4d9aa51d-05f3-498d-9b42-6947d36edd5e)


Can you try the `standalone` build please, and uninstall `librocksdb-dev`

**Comment by gsmachado** [comment]
so... let me give you a bit more context:

I install the neo-express with the following command:

`dotnet tool install Neo.Express -g --version 3.7.3`

Actually, you can check how we do things [in this repo](https://github.com/neow3j/neow3j-test-docker), more specifically [in this line](https://github.com/neow3j/neow3j-test-docker/blob/826d9dbb1cb66bb1bdb2d7acee9ed6d2fe90d37b/Dockerfile#L40).

**Comment by gsmachado** [comment]
Ok, @chenzhitong @cschuchardt88, here are the steps to reproduce:

1. Run a plain docker container just mounting the `default.neo-express` and `setup.batch` files I provided [here](https://github.com/neo-project/neo-express/issues/455#issue-2409677598).

```shell
docker run -it \
    -v $(pwd)/default.neo-express:/neoxp/default.neo-express \ 
    -v $(pwd)/setup.batch:/neoxp/setup.batch \
    -w /neoxp \
    ubuntu:noble \
    bash
```

2. Once you get the bash prompt in the docker container, just update packages and install `wget`:

```shell
apt-get update -y && apt-get install wget
```

3) Fetch the `Neo Express` version `3.7.4`. If you run your docker using `arm64`, please update the URL accordingly.

```shell
wget https://github.com/neo-project/neo-express/releases/download/3.7.3/Neo.Express-linux-x64-3.7.3.tar.gz
```

4) Uncompress the files:

```shell
tar -xvzf Neo.Express-linux-x64-3.7.3.tar.gz
```

5) You need to set this env variable to be able to run the `neoxp` binary, so let's set for this bash session only (since it's just a test):

```shell
export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
```

6) Then, try to run this command a couple of times:

```shell
./neoxp batch -i default -r setup.batch
```

👉 Please, let me know if you could make the batch process hang forever. 😸

**Comment by gsmachado** [comment]
Also, I tried the following:

I just took `ghcr.io/cschuchardt88/neo-cli:3.8.0` and used it in Step (1) of [this comment](https://github.com/neo-project/neo-express/issues/455#issuecomment-2231709372) instead of `ubuntu:noble`, and I achieved the same result: batch was hanging sometimes (not always, though!).

**Comment by vncoelho** [comment]
@gsmachado, I am struggling with this for almost 1 month!
Let's simple, at least, revert the PR that made this and then work.
This is destroying my workflow COMPLETELY.

**Comment by mialbu** [comment]
This bug is blocking neow3j from releasing a Neo-3.7.x-compatible version. Additionally, by blocking neow3j from releasing a Neo-3.7.x-compatible version, it's also blocking a desired feature (`keccak256`) to be used in the development of the native bridge to Neo X. Therefore, we really need this fixed as soon as possible.

**Comment by cschuchardt88** [comment]
@mialbu @gsmachado 
all looks good, unless you have more use cases, i can test. I will see if i can get a release sometime next week.

**Comment by gsmachado** [comment]
I can confirm that the fix works! Not hanging anymore.

Great work, team! @cschuchardt88 @chenzhitong @Jim8y

**Comment by Jim8y** [comment]
credit goes to @cschuchardt88 , he such a productive and senior developer.

**Comment by mialbu** [comment]
> I will see if i can get a release sometime next week.

Hey @cschuchardt88, can you give me an ETA for a release with this fix? Do you think it's possible to publish a new release early next week?
