### ISSUE TITLE
Invalid JavaScript property identifier character

### ISSUE THREAD

**Issue by NarubyRiverlione** [neo-project/neo-express#64]
Gas related commands give all the error `'Invalid JavaScript property identifier character: -.` after the transfer from the genesis block

OSX 10.15.6
node 12.18.3 (via nvm)

Step the reproduce the error

- run 0 -r
- wallet create dev
- show coin Dev
  []

- show gas Dev
 Unclaimed GAS for Dev: 0
    Available GAS: 0
  Unavailable GAS: 0

So far so good.

- transfer neo 10 genesis Dev
 Transfer Transaction 0x51b1864e3ea0ee0f3c25aec6e0e4c9fecb37d5a5a9858c6f82c571a7f734a0fa submitted

- show account Dev
Account information for Dev:
  Asset 0xc56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b: 10

- show gas Dev
Invalid JavaScript property identifier character: -. Path 'result.unavailable', line 1, position 52.

- show claimable Dev
Invalid JavaScript property identifier character: -. Path 'result.claimable[0].generated', line 1, position 178.

**Comment by devhawk** [comment]
Thanks for the bug report @NarubyRiverlione. I just verified the `show gas` and `show claimable` operations work on Windows. I'll bust out my MacBook and try it over there.

**Comment by devhawk** [comment]
@NarubyRiverlione I just tried this on my macbook using v1.1.28 of Neo express and did not see the issue you reported.

My MacBook Air is running MacOS 10.15.4. I'm running .net core 3.1.302 with the following runtimes:

* Microsoft.AspNetCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
* Microsoft.NETCore.App 2.1.20 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
* Microsoft.NETCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by devhawk** [comment]
@NarubyRiverlione I'm going to close this as no repro. Please feel free to open a new issue if you're still experiencing this issue
