### ISSUE TITLE
`nxp3 contract invoke ...` error message is not helpful when trying to invoke a contract that is not deployed

### ISSUE THREAD

**Issue by djnicholson** [neo-project/neo-express#93]
When a user tries to invoke a contract they have not deployed they will see an error like this: `Invalid contract value "DevHawk.Registrar" [FormatException]`

**Comment by devhawk** [comment]
What should it return @djnicholson ?

**Comment by djnicholson** [comment]
`FormatException` makes me thing I typed the name wrong (e.g. used a character that wasn't allowed, or accidentally pasted in some invisible unicode points).  I think it would be better if we removed `FormatException` entirely and maybe added something like `contract not found` or `contract not deployed`
