### ISSUE TITLE
`nxp3 run` gives a cryptic error if run while an offline operation is in progress

### ISSUE THREAD

**Issue by djnicholson** [neo-project/neo-express#95]
To repro run the following two commands in very quick (e.g. less than 500ms) succession:

```
nxp3 contract list
nxp3 run
```

`nxp3 run` will give you an error like this:

![image](https://user-images.githubusercontent.com/2515705/103391333-cba0db80-4acd-11eb-83ce-2f1dbecf7f96.png)

That's a bit hard to debug.  I think it would be better to have the offline operation create a mutex and then use that to give a meaningful error (like we do if you try to run the same blockchain more than once).

**Comment by devhawk** [comment]
I just tested running neoxp run on the same express instance in two separate windows. I get the following error: 

```
IO error: Failed to create lock file: C:\Users\harry\AppData\Local\Neo-Express\blockchain-nodes\NgzDbx8se6NJxzKvdYRBgmk41G8ywfDtXp/LOCK: The process cannot access the file because it is being used by another process.
```

Is this reasonable to debug?

**Comment by devhawk** [comment]
We primarily use the mutex to detect if the blockchain is running so we can automatically choose online vs offline mode for operations like contract deploy and transfer. I will take a look to see about using it for better error messages in cases like this

**Comment by devhawk** [comment]
> This issue wasn't about running Neo Express twice simultaneously, BTW :)

Yeah, that's just the easiest way to trigger the issue!

**Comment by djnicholson** [comment]
> We primarily use the mutex to detect if the blockchain is running so we can automatically choose online vs offline mode for operations like contract deploy and transfer. I will take a look to see about using it for better error messages in cases like this

That makes sense now - I knew we were using a mutex somewhere but had forgotten where!
