### ISSUE TITLE
Read-only offline operations should not need exclusive access to the rocksdb

### ISSUE THREAD

**Issue by djnicholson** [neo-project/neo-express#96]
Can readonly operations (e.g. `contract list`, `contract get`, ...) read from the data store without taking a lock (like a secondary node in a multi-node setup) so that they don't prevent the chain from being run while in progress?

**Comment by devhawk** [comment]
Run needs write access. Even if rocksdb supports multiple read-only access clients, I suspect that run would still need exclusive access.

**Comment by djnicholson** [comment]
I would expect run to need exclusive access.  This issue was more about things like getting contract info, wallet balances, etc.

**Comment by devhawk** [comment]
so if run needs exclusive access, wouldn't a read only lock (if that was feasible) prevent the chain from being run while in progress?
